import UIKit

// ============================================================
// ⚠️ AUTO-GENERATED by tools/sync-design-tokens.swift
// DO NOT EDIT — changes will be overwritten on next sync.
// Source: docs/design-tokens.json
// Generated: 2026-05-08T04:22:19Z
// ============================================================

public enum ThemeTokens {

    // DEPRECATED: Use ThemeTokens.Color instead (auto-adapts to Dark Mode)
    public enum Colors {
        public enum Light {
            public static let background = UIColor(red: 0.9490196078431372, green: 0.9490196078431372, blue: 0.9686274509803922, alpha: 1)
            public static let badgeBackground = UIColor(red: 0.9490196078431372, green: 0.9490196078431372, blue: 0.9686274509803922, alpha: 1)
            public static let badgeText = UIColor(red: 0.38823529411764707, green: 0.38823529411764707, blue: 0.4, alpha: 1)
            public static let border = UIColor(red: 0.7764705882352941, green: 0.7764705882352941, blue: 0.7843137254901961, alpha: 1)
            public static let cardBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let error = UIColor(red: 1.0, green: 0.23137254901960785, blue: 0.18823529411764706, alpha: 1)
            public static let fabBackground = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let gradientEnd = UIColor(red: 0.6, green: 0.30196078431372547, blue: 0.7490196078431373, alpha: 0.85)
            public static let gradientStart = UIColor(red: 0.25098039215686274, green: 0.45098039215686275, blue: 0.9490196078431372, alpha: 0.85)
            public static let info = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let navigationBarBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let overlay = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.4)
            public static let primary = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let secondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let separator = UIColor(red: 0.7764705882352941, green: 0.7764705882352941, blue: 0.7843137254901961, alpha: 1)
            public static let success = UIColor(red: 0.20392156862745098, green: 0.7803921568627451, blue: 0.34901960784313724, alpha: 1)
            public static let surface = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let tabBarBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let text = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let textSecondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let textTertiary = UIColor(red: 0.7803921568627451, green: 0.7803921568627451, blue: 0.8, alpha: 1)
            public static let unreadDot = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let warning = UIColor(red: 1.0, green: 0.5843137254901961, blue: 0.0, alpha: 1)
        }

        public enum Dark {
            public static let background = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let badgeBackground = UIColor(red: 0.2, green: 0.2, blue: 0.25098039215686274, alpha: 1)
            public static let badgeText = UIColor(red: 0.9215686274509803, green: 0.9215686274509803, blue: 0.9607843137254902, alpha: 1)
            public static let border = UIColor(red: 0.2196078431372549, green: 0.2196078431372549, blue: 0.22745098039215686, alpha: 1)
            public static let cardBackground = UIColor(red: 0.14901960784313725, green: 0.14901960784313725, blue: 0.16862745098039217, alpha: 1)
            public static let error = UIColor(red: 1.0, green: 0.27058823529411763, blue: 0.22745098039215686, alpha: 1)
            public static let fabBackground = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let gradientEnd = UIColor(red: 0.4, green: 0.2, blue: 0.5019607843137255, alpha: 0.9)
            public static let gradientStart = UIColor(red: 0.2, green: 0.30196078431372547, blue: 0.6, alpha: 0.9)
            public static let info = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let navigationBarBackground = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let overlay = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.6)
            public static let primary = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let secondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let separator = UIColor(red: 0.2196078431372549, green: 0.2196078431372549, blue: 0.22745098039215686, alpha: 1)
            public static let success = UIColor(red: 0.18823529411764706, green: 0.8196078431372549, blue: 0.34509803921568627, alpha: 1)
            public static let surface = UIColor(red: 0.10980392156862745, green: 0.10980392156862745, blue: 0.11764705882352941, alpha: 1)
            public static let tabBarBackground = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let text = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let textSecondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let textTertiary = UIColor(red: 0.2823529411764706, green: 0.2823529411764706, blue: 0.2901960784313726, alpha: 1)
            public static let unreadDot = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let warning = UIColor(red: 1.0, green: 0.6235294117647059, blue: 0.0392156862745098, alpha: 1)
        }
    }

    // === Dynamic Color aliases (the ONE way to get colors) ===
    /// 动态颜色令牌 — 自动适配 Light/Dark Mode
    /// 所有新代码必须使用 ThemeTokens.Color.* 而非 ThemeTokens.Colors.Light/Dark 或直接硬编码
    public enum Color {
        public static var primary: UIColor { ThemeColors.current.primary }
        public static var secondary: UIColor { ThemeColors.current.secondary }
        public static var background: UIColor { ThemeColors.current.background }
        public static var surface: UIColor { ThemeColors.current.surface }
        public static var text: UIColor { ThemeColors.current.text }
        public static var textSecondary: UIColor { ThemeColors.current.textSecondary }
        public static var textTertiary: UIColor { ThemeColors.current.border }
        public static var border: UIColor { ThemeColors.current.border }
        public static var separator: UIColor { ThemeColors.current.divider }
        public static var divider: UIColor { ThemeColors.current.divider }
        public static var navigationBarBackground: UIColor { ThemeColors.current.navigationBarBackground }
        public static var navigationBarTitle: UIColor { ThemeColors.current.navigationBarTitle }
        public static var tabBarBackground: UIColor { ThemeColors.current.tabBarBackground }
        public static var success: UIColor { ThemeColors.current.success }
        public static var warning: UIColor { ThemeColors.current.warning }
        public static var error: UIColor { ThemeColors.current.error }
        public static var info: UIColor { ThemeColors.current.info }
        public static var cardBackground: UIColor { ThemeColors.current.cardBackground }
        public static var gradientStart: UIColor { ThemeColors.current.gradientStart }
        public static var gradientEnd: UIColor { ThemeColors.current.gradientEnd }
        public static var badgeBackground: UIColor { ThemeColors.current.badgeBackground }
        public static var badgeText: UIColor { ThemeColors.current.badgeText }
        public static var fabBackground: UIColor { ThemeColors.current.fabBackground }
        public static var overlay: UIColor { ThemeTokens.Color.dimOverlay }
        public static var unreadDot: UIColor { ThemeTokens.Color.primary }

        public static var iconBackground: UIColor {
            primary.withAlphaComponent(0.1)
        }

        public static var dimOverlay: UIColor {
            UIColor(white: 0, alpha: 0.4)
        }
    }

    public enum Typography {
        public static let body = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 17, weight: .regular))
        public static let callout = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 16, weight: .regular))
        public static let caption1 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 12, weight: .regular))
        public static let caption2 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 11, weight: .regular))
        public static let footnote = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 13, weight: .regular))
        public static let headline = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 17, weight: .semibold))
        public static let largeTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let subheadline = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 15, weight: .regular))
        public static let title1 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let title2 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 22, weight: .bold))
        public static let title3 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 20, weight: .semibold))
    }

    public enum Spacing {
        public static let lg: CGFloat = 24.0
        public static let md: CGFloat = 16.0
        public static let sm: CGFloat = 8.0
        public static let xl: CGFloat = 32.0
        public static let xs: CGFloat = 4.0
        public static let xxl: CGFloat = 48.0
    }

    public enum CornerRadius {
        public static let full: CGFloat = 999.0
        public static let lg: CGFloat = 12.0
        public static let md: CGFloat = 8.0
        public static let sm: CGFloat = 4.0
        public static let xl: CGFloat = 16.0
        public static let xs: CGFloat = 2.0
        public static let xxl: CGFloat = 20.0
    }

    public enum Shadows {
        public static let Card = ShadowValues(opacity: 0.08, offsetX: 0.0, offsetY: 4.0, radius: 12.0)
        public static let Fab = ShadowValues(opacity: 0.3, offsetX: 0.0, offsetY: 4.0, radius: 8.0)
        public static let Modal = ShadowValues(opacity: 0.15, offsetX: 0.0, offsetY: 8.0, radius: 24.0)
        public static let NavBar = ShadowValues(opacity: 0.03, offsetX: 0.0, offsetY: 2.0, radius: 8.0)
        public static let Tooltip = ShadowValues(opacity: 0.12, offsetX: 0.0, offsetY: 2.0, radius: 4.0)
    }

    public enum Opacity {
        public static let badge: CGFloat = 0.12
        public static let disabled: CGFloat = 0.3
        public static let hover: CGFloat = 0.8
        public static let overlay: CGFloat = 0.4
        public static let placeholder: CGFloat = 0.4
        public static let pressed: CGFloat = 0.6
    }

    public enum Animation {
        public static let fast = AnimationValues(duration: 0.15)
        public static let modal = AnimationValues(duration: 0.5)
        public static let normal = AnimationValues(duration: 0.25)
        public static let slow = AnimationValues(duration: 0.35)
        public static let spring = AnimationValues(duration: 0.3, damping: 0.8)
    }

    public enum Icons {
        public enum Sizes {
            public static let lg: CGFloat = 24.0
            public static let md: CGFloat = 20.0
            public static let sm: CGFloat = 16.0
            public static let xl: CGFloat = 32.0
            public static let xs: CGFloat = 12.0
            public static let xxl: CGFloat = 48.0
        }
    }

    public enum Breakpoints {
        public static let compact: CGFloat = 320.0
        public static let large: CGFloat = 428.0
        public static let regular: CGFloat = 375.0
    }
}

public struct ShadowValues: Sendable {
    public let opacity: CGFloat
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let radius: CGFloat
}

public struct AnimationValues: Sendable {
    public let duration: TimeInterval
    public let damping: CGFloat

    public init(duration: TimeInterval, damping: CGFloat = 1.0) {
        self.duration = duration
        self.damping = damping
    }
}
