import UIKit

// ============================================================
// AUTO-GENERATED by tools/sync-design-tokens.swift
// DO NOT EDIT — changes will be overwritten on next sync.
// Source: docs/design-tokens.json
// Generated: 2026-05-24T02:59:41Z
// ============================================================

public enum ThemeTokens {

    // DEPRECATED: Use ThemeTokens.Color instead (auto-adapts to Dark Mode)
    public enum Colors {
        public enum Light {
            public static let accent = UIColor(red: 0.5450980392156862, green: 0.3607843137254902, blue: 0.9647058823529412, alpha: 1)
            public static let accentSoft = UIColor(red: 0.9529411764705882, green: 0.9372549019607843, blue: 0.996078431372549, alpha: 1)
            public static let background = UIColor(red: 0.9725490196078431, green: 0.9764705882352941, blue: 0.9882352941176471, alpha: 1)
            public static let backgroundSecondary = UIColor(red: 0.9411764705882353, green: 0.9490196078431372, blue: 0.9686274509803922, alpha: 1)
            public static let backgroundTertiary = UIColor(red: 0.9098039215686274, green: 0.9215686274509803, blue: 0.9490196078431372, alpha: 1)
            public static let border = UIColor(red: 0.8470588235294118, green: 0.8705882352941177, blue: 0.9098039215686274, alpha: 1)
            public static let cardBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let error = UIColor(red: 0.8627450980392157, green: 0.14901960784313725, blue: 0.14901960784313725, alpha: 1)
            public static let errorSoft = UIColor(red: 0.996078431372549, green: 0.9254901960784314, blue: 0.9254901960784314, alpha: 1)
            public static let info = UIColor(red: 0.058823529411764705, green: 0.4627450980392157, blue: 0.43137254901960786, alpha: 1)
            public static let infoSoft = UIColor(red: 0.9058823529411765, green: 0.9647058823529412, blue: 0.9568627450980393, alpha: 1)
            public static let navigationBarBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let offline = UIColor(red: 0.39215686274509803, green: 0.4549019607843137, blue: 0.5450980392156862, alpha: 1)
            public static let offlineSoft = UIColor(red: 0.9333333333333333, green: 0.9490196078431372, blue: 0.9647058823529412, alpha: 1)
            public static let overlay = UIColor(red: 0.06666666666666667, green: 0.09411764705882353, blue: 0.15294117647058825, alpha: 0.42)
            public static let placeholder = UIColor(red: 0.6470588235294118, green: 0.6784313725490196, blue: 0.7294117647058823, alpha: 1)
            public static let primary = UIColor(red: 0.30980392156862746, green: 0.41568627450980394, blue: 0.9647058823529412, alpha: 1)
            public static let primaryPressed = UIColor(red: 0.23921568627450981, green: 0.33725490196078434, blue: 0.8784313725490196, alpha: 1)
            public static let primarySoft = UIColor(red: 0.9333333333333333, green: 0.9450980392156862, blue: 0.996078431372549, alpha: 1)
            public static let separator = UIColor(red: 0.9019607843137255, green: 0.9176470588235294, blue: 0.9411764705882353, alpha: 1)
            public static let shadow = UIColor(red: 0.06666666666666667, green: 0.09411764705882353, blue: 0.15294117647058825, alpha: 0.1)
            public static let success = UIColor(red: 0.08627450980392157, green: 0.6392156862745098, blue: 0.2901960784313726, alpha: 1)
            public static let successSoft = UIColor(red: 0.9176470588235294, green: 0.9725490196078431, blue: 0.9372549019607843, alpha: 1)
            public static let surface = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let surfaceElevated = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let tabBarBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let text = UIColor(red: 0.10196078431372549, green: 0.11372549019607843, blue: 0.1803921568627451, alpha: 1)
            public static let textSecondary = UIColor(red: 0.4196078431372549, green: 0.45098039215686275, blue: 0.5803921568627451, alpha: 1)
            public static let textTertiary = UIColor(red: 0.611764705882353, green: 0.6392156862745098, blue: 0.7686274509803922, alpha: 1)
            public static let warning = UIColor(red: 0.8509803921568627, green: 0.4666666666666667, blue: 0.023529411764705882, alpha: 1)
            public static let warningSoft = UIColor(red: 1.0, green: 0.9568627450980393, blue: 0.8980392156862745, alpha: 1)
        }

        public enum Dark {
            public static let accent = UIColor(red: 0.6549019607843137, green: 0.5450980392156862, blue: 0.9803921568627451, alpha: 1)
            public static let accentSoft = UIColor(red: 0.6549019607843137, green: 0.5450980392156862, blue: 0.9803921568627451, alpha: 0.14)
            public static let background = UIColor(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.09019607843137255, alpha: 1)
            public static let backgroundSecondary = UIColor(red: 0.10196078431372549, green: 0.11372549019607843, blue: 0.1568627450980392, alpha: 1)
            public static let backgroundTertiary = UIColor(red: 0.1450980392156863, green: 0.16470588235294117, blue: 0.2196078431372549, alpha: 1)
            public static let border = UIColor(red: 0.16470588235294117, green: 0.19607843137254902, blue: 0.23921568627450981, alpha: 1)
            public static let cardBackground = UIColor(red: 0.11764705882352941, green: 0.13333333333333333, blue: 0.2, alpha: 1)
            public static let error = UIColor(red: 0.9725490196078431, green: 0.44313725490196076, blue: 0.44313725490196076, alpha: 1)
            public static let errorSoft = UIColor(red: 0.9725490196078431, green: 0.44313725490196076, blue: 0.44313725490196076, alpha: 0.14)
            public static let info = UIColor(red: 0.17647058823529413, green: 0.8313725490196079, blue: 0.7490196078431373, alpha: 1)
            public static let infoSoft = UIColor(red: 0.17647058823529413, green: 0.8313725490196079, blue: 0.7490196078431373, alpha: 0.13)
            public static let navigationBarBackground = UIColor(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.09019607843137255, alpha: 1)
            public static let offline = UIColor(red: 0.5803921568627451, green: 0.6392156862745098, blue: 0.7215686274509804, alpha: 1)
            public static let offlineSoft = UIColor(red: 0.5803921568627451, green: 0.6392156862745098, blue: 0.7215686274509804, alpha: 0.13)
            public static let overlay = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.58)
            public static let placeholder = UIColor(red: 0.4, green: 0.4392156862745098, blue: 0.5215686274509804, alpha: 1)
            public static let primary = UIColor(red: 0.4196078431372549, green: 0.5098039215686274, blue: 0.9725490196078431, alpha: 1)
            public static let primaryPressed = UIColor(red: 0.30980392156862746, green: 0.41568627450980394, blue: 0.9647058823529412, alpha: 1)
            public static let primarySoft = UIColor(red: 0.4196078431372549, green: 0.5098039215686274, blue: 0.9725490196078431, alpha: 0.14)
            public static let separator = UIColor(red: 0.13725490196078433, green: 0.16470588235294117, blue: 0.20392156862745098, alpha: 1)
            public static let shadow = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.3)
            public static let success = UIColor(red: 0.2901960784313726, green: 0.8705882352941177, blue: 0.5019607843137255, alpha: 1)
            public static let successSoft = UIColor(red: 0.2901960784313726, green: 0.8705882352941177, blue: 0.5019607843137255, alpha: 0.13)
            public static let surface = UIColor(red: 0.07450980392156863, green: 0.09019607843137255, blue: 0.11372549019607843, alpha: 1)
            public static let surfaceElevated = UIColor(red: 0.09803921568627451, green: 0.11764705882352941, blue: 0.14901960784313725, alpha: 1)
            public static let tabBarBackground = UIColor(red: 0.06274509803921569, green: 0.0784313725490196, blue: 0.10196078431372549, alpha: 1)
            public static let text = UIColor(red: 0.9411764705882353, green: 0.9490196078431372, blue: 0.9686274509803922, alpha: 1)
            public static let textSecondary = UIColor(red: 0.5333333333333333, green: 0.5725490196078431, blue: 0.6901960784313725, alpha: 1)
            public static let textTertiary = UIColor(red: 0.3607843137254902, green: 0.396078431372549, blue: 0.5215686274509804, alpha: 1)
            public static let warning = UIColor(red: 0.984313725490196, green: 0.7490196078431373, blue: 0.1411764705882353, alpha: 1)
            public static let warningSoft = UIColor(red: 0.984313725490196, green: 0.7490196078431373, blue: 0.1411764705882353, alpha: 0.14)
        }
    }

    // === Dynamic Color aliases (the ONE way to get colors) ===
    /// Dynamic color tokens — auto-adapt to Light/Dark Mode.
    /// New code must use ThemeTokens.Color.* instead of ThemeTokens.Colors.Light/Dark or hardcoded UIColor values.
    public enum Color {
        public static var accent: UIColor { dynamicColor(light: Colors.Light.accent, dark: Colors.Dark.accent) }
        public static var accentSoft: UIColor { dynamicColor(light: Colors.Light.accentSoft, dark: Colors.Dark.accentSoft) }
        public static var background: UIColor { dynamicColor(light: Colors.Light.background, dark: Colors.Dark.background) }
        public static var backgroundSecondary: UIColor { dynamicColor(light: Colors.Light.backgroundSecondary, dark: Colors.Dark.backgroundSecondary) }
        public static var backgroundTertiary: UIColor { dynamicColor(light: Colors.Light.backgroundTertiary, dark: Colors.Dark.backgroundTertiary) }
        public static var border: UIColor { dynamicColor(light: Colors.Light.border, dark: Colors.Dark.border) }
        public static var cardBackground: UIColor { dynamicColor(light: Colors.Light.cardBackground, dark: Colors.Dark.cardBackground) }
        public static var error: UIColor { dynamicColor(light: Colors.Light.error, dark: Colors.Dark.error) }
        public static var errorSoft: UIColor { dynamicColor(light: Colors.Light.errorSoft, dark: Colors.Dark.errorSoft) }
        public static var info: UIColor { dynamicColor(light: Colors.Light.info, dark: Colors.Dark.info) }
        public static var infoSoft: UIColor { dynamicColor(light: Colors.Light.infoSoft, dark: Colors.Dark.infoSoft) }
        public static var navigationBarBackground: UIColor { dynamicColor(light: Colors.Light.navigationBarBackground, dark: Colors.Dark.navigationBarBackground) }
        public static var offline: UIColor { dynamicColor(light: Colors.Light.offline, dark: Colors.Dark.offline) }
        public static var offlineSoft: UIColor { dynamicColor(light: Colors.Light.offlineSoft, dark: Colors.Dark.offlineSoft) }
        public static var overlay: UIColor { dynamicColor(light: Colors.Light.overlay, dark: Colors.Dark.overlay) }
        public static var placeholder: UIColor { dynamicColor(light: Colors.Light.placeholder, dark: Colors.Dark.placeholder) }
        public static var primary: UIColor { dynamicColor(light: Colors.Light.primary, dark: Colors.Dark.primary) }
        public static var primaryPressed: UIColor { dynamicColor(light: Colors.Light.primaryPressed, dark: Colors.Dark.primaryPressed) }
        public static var primarySoft: UIColor { dynamicColor(light: Colors.Light.primarySoft, dark: Colors.Dark.primarySoft) }
        public static var separator: UIColor { dynamicColor(light: Colors.Light.separator, dark: Colors.Dark.separator) }
        public static var shadow: UIColor { dynamicColor(light: Colors.Light.shadow, dark: Colors.Dark.shadow) }
        public static var success: UIColor { dynamicColor(light: Colors.Light.success, dark: Colors.Dark.success) }
        public static var successSoft: UIColor { dynamicColor(light: Colors.Light.successSoft, dark: Colors.Dark.successSoft) }
        public static var surface: UIColor { dynamicColor(light: Colors.Light.surface, dark: Colors.Dark.surface) }
        public static var surfaceElevated: UIColor { dynamicColor(light: Colors.Light.surfaceElevated, dark: Colors.Dark.surfaceElevated) }
        public static var tabBarBackground: UIColor { dynamicColor(light: Colors.Light.tabBarBackground, dark: Colors.Dark.tabBarBackground) }
        public static var text: UIColor { dynamicColor(light: Colors.Light.text, dark: Colors.Dark.text) }
        public static var textSecondary: UIColor { dynamicColor(light: Colors.Light.textSecondary, dark: Colors.Dark.textSecondary) }
        public static var textTertiary: UIColor { dynamicColor(light: Colors.Light.textTertiary, dark: Colors.Dark.textTertiary) }
        public static var warning: UIColor { dynamicColor(light: Colors.Light.warning, dark: Colors.Dark.warning) }
        public static var warningSoft: UIColor { dynamicColor(light: Colors.Light.warningSoft, dark: Colors.Dark.warningSoft) }

        // Compatibility aliases used by existing components.
        public static var badgeBackground: UIColor { primarySoft }
        public static var badgeText: UIColor { textSecondary }
        public static var dimOverlay: UIColor { overlay }
        public static var divider: UIColor { separator }
        public static var fabBackground: UIColor { primary }
        public static var gradientEnd: UIColor { dynamicColor(light: UIColor(red: 0.6, green: 0.30196078431372547, blue: 0.7490196078431373, alpha: 0.85), dark: UIColor(red: 0.4, green: 0.2, blue: 0.5019607843137255, alpha: 0.9)) }
        public static var gradientStart: UIColor { dynamicColor(light: UIColor(red: 0.25098039215686274, green: 0.45098039215686275, blue: 0.9490196078431372, alpha: 0.85), dark: UIColor(red: 0.2, green: 0.30196078431372547, blue: 0.6, alpha: 0.9)) }
        public static var iconBackground: UIColor { dynamicColor(light: UIColor(red: 0.30980392156862746, green: 0.41568627450980394, blue: 0.9647058823529412, alpha: 0.1), dark: UIColor(red: 0.4196078431372549, green: 0.5098039215686274, blue: 0.9725490196078431, alpha: 0.1)) }
        public static var navigationBarTitle: UIColor { text }
        public static var onPrimary: UIColor { textOnColor }
        public static var overlaySoft: UIColor { dynamicColor(light: UIColor(red: 0.06666666666666667, green: 0.09411764705882353, blue: 0.15294117647058825, alpha: 0.2), dark: UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.3)) }
        public static var overlayStrong: UIColor { dynamicColor(light: UIColor(red: 0.06666666666666667, green: 0.09411764705882353, blue: 0.15294117647058825, alpha: 0.7), dark: UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.8)) }
        public static var scrim: UIColor { overlay }
        public static var secondary: UIColor { textSecondary }
        public static var textOnColor: UIColor { dynamicColor(light: UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)) }
        public static var unreadDot: UIColor { primary }

        private static func dynamicColor(light: UIColor, dark: UIColor) -> UIColor {
            UIColor { trait in
                trait.userInterfaceStyle == .dark ? dark : light
            }
        }
    }

    public enum Typography {
        public static let badge = UIFontMetrics(forTextStyle: .caption2).scaledFont(for: .systemFont(ofSize: 10, weight: .bold))
        public static let body = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .regular))
        public static let button = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .semibold))
        public static let buttonMedium = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .medium))
        public static let caption = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: .systemFont(ofSize: 12, weight: .regular))
        public static let cardTitle = UIFontMetrics(forTextStyle: .subheadline).scaledFont(for: .systemFont(ofSize: 16, weight: .semibold))
        public static let compactTitle = UIFontMetrics(forTextStyle: .title1).scaledFont(for: .systemFont(ofSize: 24, weight: .bold))
        public static let display = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let displayLarge = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 34, weight: .bold))
        public static let metadata = UIFontMetrics(forTextStyle: .footnote).scaledFont(for: .systemFont(ofSize: 13, weight: .regular))
        public static let monospaceMeta = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 12, weight: .regular))
        public static let rowTitle = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 16, weight: .medium))
        public static let screenTitle = UIFontMetrics(forTextStyle: .largeTitle).scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let sectionTitle = UIFontMetrics(forTextStyle: .headline).scaledFont(for: .systemFont(ofSize: 17, weight: .semibold))
        public static let tabLabel = UIFontMetrics(forTextStyle: .caption2).scaledFont(for: .systemFont(ofSize: 11, weight: .medium))

        // Monospace variants
        public static let monospaceBody = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 13, weight: .regular))
        public static let monospaceBodyMedium = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 13, weight: .medium))
        public static let monospaceDisplay = UIFontMetrics(forTextStyle: .title2).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 20, weight: .bold))
        public static let monospaceDisplaySemibold = UIFontMetrics(forTextStyle: .title2).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 20, weight: .semibold))
        public static let monospaceLarge = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 14, weight: .regular))
        public static let monospaceLargeMedium = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 14, weight: .medium))
        public static let monospaceLargeSemibold = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 17, weight: .semibold))
        public static let monospaceMetaBold = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 12, weight: .bold))
        public static let monospaceMicro = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 9, weight: .regular))
        public static let monospaceMini = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 10, weight: .regular))
        public static let monospaceMiniMedium = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 10, weight: .medium))
        public static let monospaceSmall = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 11, weight: .regular))
        public static let monospaceSmallMedium = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 11, weight: .medium))
        public static let monospaceTitle = UIFontMetrics(forTextStyle: .title3).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 18, weight: .bold))

        // Legacy Apple text style aliases
        public static let callout = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .regular))
        public static let caption1 = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: .systemFont(ofSize: 12, weight: .regular))
        public static let caption2 = UIFontMetrics(forTextStyle: .caption2).scaledFont(for: .systemFont(ofSize: 11, weight: .medium))
        public static let footnote = UIFontMetrics(forTextStyle: .footnote).scaledFont(for: .systemFont(ofSize: 13, weight: .regular))
        public static let headline = UIFontMetrics(forTextStyle: .headline).scaledFont(for: .systemFont(ofSize: 17, weight: .semibold))
        public static let largeTitle = UIFontMetrics(forTextStyle: .largeTitle).scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let subheadline = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .regular))
        public static let title1 = UIFontMetrics(forTextStyle: .largeTitle).scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let title2 = UIFontMetrics(forTextStyle: .title1).scaledFont(for: .systemFont(ofSize: 24, weight: .bold))
        public static let title3 = UIFontMetrics(forTextStyle: .subheadline).scaledFont(for: .systemFont(ofSize: 16, weight: .semibold))
    }

    public enum Spacing {
        public static let lg: CGFloat = 16.0
        public static let md: CGFloat = 12.0
        public static let screenBottom: CGFloat = 24.0
        public static let screenHorizontal: CGFloat = 16.0
        public static let screenTop: CGFloat = 16.0
        public static let section: CGFloat = 32.0
        public static let sm: CGFloat = 8.0
        public static let xl: CGFloat = 20.0
        public static let xs: CGFloat = 4.0
        public static let xxl: CGFloat = 24.0
        public static let xxs: CGFloat = 2.0
        public static let xxxl: CGFloat = 32.0
    }

    public enum CornerRadius {
        public static let avatar: CGFloat = 22.0
        public static let card: CGFloat = 16.0
        public static let full: CGFloat = 999.0
        public static let lg: CGFloat = 12.0
        public static let md: CGFloat = 12.0
        public static let pill: CGFloat = 28.0
        public static let row: CGFloat = 12.0
        public static let sheet: CGFloat = 20.0
        public static let sm: CGFloat = 8.0
        public static let xl: CGFloat = 24.0
        public static let xs: CGFloat = 6.0
        public static let xxl: CGFloat = 20.0
    }
    public enum Shadows {
        public static let card = ShadowValues(opacity: 0.08, offsetX: 0.0, offsetY: 4.0, radius: 16.0)
        public static let floatingAction = ShadowValues(opacity: 0.2, offsetX: 0.0, offsetY: 8.0, radius: 24.0)
        public static let lg = ShadowValues(opacity: 0.12, offsetX: 0.0, offsetY: 8.0, radius: 24.0)
        public static let md = ShadowValues(opacity: 0.1, offsetX: 0.0, offsetY: 2.0, radius: 8.0)
        public static let none = ShadowValues(opacity: 0.0, offsetX: 0.0, offsetY: 0.0, radius: 0.0)
        public static let sheet = ShadowValues(opacity: 0.15, offsetX: 0.0, offsetY: 12.0, radius: 32.0)
        public static let sm = ShadowValues(opacity: 0.08, offsetX: 0.0, offsetY: 1.0, radius: 3.0)
        public static let Card = ShadowValues(opacity: 1.0, offsetX: 0.0, offsetY: 2.0, radius: 8.0)
        public static let Fab = ShadowValues(opacity: 1.0, offsetX: 0.0, offsetY: 8.0, radius: 18.0)
        public static let Modal = ShadowValues(opacity: 1.0, offsetX: 0.0, offsetY: 12.0, radius: 28.0)
        public static let NavBar = ShadowValues(opacity: 0.0, offsetX: 0.0, offsetY: 0.0, radius: 0.0)
        public static let SearchBar = ShadowValues(opacity: 0.0, offsetX: 0.0, offsetY: 0.0, radius: 0.0)
        public static let Tooltip = ShadowValues(opacity: 0.0, offsetX: 0.0, offsetY: 0.0, radius: 0.0)
    }

    public enum Opacity {
        public static let badge: CGFloat = 0.14
        public static let badgeFill: CGFloat = 0.14
        public static let disabled: CGFloat = 0.36
        public static let hover: CGFloat = 0.88
        public static let overlay: CGFloat = 0.42
        public static let placeholder: CGFloat = 0.36
        public static let pressed: CGFloat = 0.72
        public static let scrim: CGFloat = 0.42
        public static let separator: CGFloat = 0.72
    }

    public enum Animation {
        public static let fast = AnimationValues(duration: 0.15)
        public static let modal = AnimationValues(duration: 0.36, damping: 0.88)
        public static let normal = AnimationValues(duration: 0.25)
        public static let sheet = AnimationValues(duration: 0.36, damping: 0.88)
        public static let slow = AnimationValues(duration: 0.4)
        public static let spring = AnimationValues(duration: 0.5, damping: 0.85, velocity: 0.5)
    }

    public enum Icons {
        public enum Sizes {
            public static let chevron: CGFloat = 16.0
            public static let empty: CGFloat = 48.0
            public static let lg: CGFloat = 24.0
            public static let md: CGFloat = 20.0
            public static let quickAction: CGFloat = 22.0
            public static let settings: CGFloat = 20.0
            public static let sm: CGFloat = 16.0
            public static let tab: CGFloat = 23.0
            public static let xl: CGFloat = 24.0
            public static let xs: CGFloat = 14.0
            public static let xxl: CGFloat = 48.0
        }
    }

    public enum Breakpoints {
        public static let compact: CGFloat = 320.0
        public static let large: CGFloat = 428.0
        public static let regular: CGFloat = 375.0
    }

    public enum ComponentContract {
        public enum ActionTile {
            public static let height: CGFloat = 72.0
            public static let iconSize: CGFloat = 22.0
            public static let minWidth: CGFloat = 72.0
            public static let titleMaxLines: CGFloat = 1.0
        }
        public enum Button {
            public static let cornerRadius: CGFloat = 12.0
            public static let height: CGFloat = 48.0
            public static let horizontalPadding: CGFloat = 20.0
            public static let iconSize: CGFloat = 18.0
        }
        public enum EmptyState {
            public static let bodySize: CGFloat = 13.0
            public static let iconSize: CGFloat = 48.0
            public static let maxWidth: CGFloat = 280.0
            public static let requiresPrimaryAction: Bool = true
            public static let titleSize: CGFloat = 17.0
        }
        public enum FilterPill {
            public static let height: CGFloat = 34.0
            public static let horizontalPadding: CGFloat = 14.0
            public static let minWidth: CGFloat = 56.0
        }
        public enum MessageCell {
            public static let bodyMaxLines: CGFloat = 2.0
            public static let maxHeight: CGFloat = 96.0
            public static let minHeight: CGFloat = 72.0
            public static let titleMaxLines: CGFloat = 1.0
        }
        public enum ResourceCard {
            public static let cornerRadius: CGFloat = 16.0
            public static let iconSize: CGFloat = 22.0
            public static let maxHeight: CGFloat = 116.0
            public static let metadataMaxLines: CGFloat = 1.0
            public static let minHeight: CGFloat = 92.0
            public static let padding: CGFloat = 16.0
            public static let titleMaxLines: CGFloat = 2.0
        }
        public enum Screen {
            public static let horizontalInset: CGFloat = 16.0
            public static let interSectionSpacing: CGFloat = 24.0
            public static let safeAreaRequired: Bool = true
        }
        public enum SearchField {
            public static let cornerRadius: CGFloat = 12.0
            public static let height: CGFloat = 44.0
            public static let horizontalPadding: CGFloat = 12.0
            public static let iconSize: CGFloat = 18.0
        }
        public enum SettingsRow {
            public static let chevronSize: CGFloat = 16.0
            public static let horizontalPadding: CGFloat = 16.0
            public static let iconBox: CGFloat = 32.0
            public static let iconSize: CGFloat = 20.0
            public static let maxHeight: CGFloat = 64.0
            public static let minHeight: CGFloat = 54.0
            public static let titleMaxLines: CGFloat = 1.0
        }
        public enum TabBar {
            public static let contentTopPadding: CGFloat = 6.0
            public static let height: CGFloat = 56.0
            public static let iconSize: CGFloat = 23.0
            public static let labelSize: CGFloat = 11.0
            public static let mustNotOverlapScrollContent: Bool = true
        }
        public enum TapTarget {
            public static let minimumHeight: CGFloat = 44.0
            public static let minimumWidth: CGFloat = 44.0
        }
    }

    public enum Gradients {
        public static let blue = GradientValues(start: UIColor(red: 0.30980392156862746, green: 0.41568627450980394, blue: 0.9647058823529412, alpha: 1), end: UIColor(red: 0.2196078431372549, green: 0.7411764705882353, blue: 0.9725490196078431, alpha: 1), angle: 135.0)
        public static let brand = GradientValues(start: UIColor(red: 0.30980392156862746, green: 0.41568627450980394, blue: 0.9647058823529412, alpha: 1), end: UIColor(red: 0.5450980392156862, green: 0.3607843137254902, blue: 0.9647058823529412, alpha: 1), angle: 135.0)
        public static let cyan = GradientValues(start: UIColor(red: 0.023529411764705882, green: 0.7137254901960784, blue: 0.8313725490196079, alpha: 1), end: UIColor(red: 0.403921568627451, green: 0.9098039215686274, blue: 0.9764705882352941, alpha: 1), angle: 135.0)
        public static let green = GradientValues(start: UIColor(red: 0.06274509803921569, green: 0.7254901960784313, blue: 0.5058823529411764, alpha: 1), end: UIColor(red: 0.20392156862745098, green: 0.8274509803921568, blue: 0.6, alpha: 1), angle: 135.0)
        public static let orange = GradientValues(start: UIColor(red: 0.9607843137254902, green: 0.6196078431372549, blue: 0.043137254901960784, alpha: 1), end: UIColor(red: 0.984313725490196, green: 0.5725490196078431, blue: 0.23529411764705882, alpha: 1), angle: 135.0)
        public static let peach = GradientValues(start: UIColor(red: 0.984313725490196, green: 0.44313725490196076, blue: 0.5215686274509804, alpha: 1), end: UIColor(red: 0.9921568627450981, green: 0.7294117647058823, blue: 0.4549019607843137, alpha: 1), angle: 135.0)
        public static let pink = GradientValues(start: UIColor(red: 0.9254901960784314, green: 0.2823529411764706, blue: 0.6, alpha: 1), end: UIColor(red: 0.9568627450980393, green: 0.4470588235294118, blue: 0.7137254901960784, alpha: 1), angle: 135.0)
        public static let purple = GradientValues(start: UIColor(red: 0.5450980392156862, green: 0.3607843137254902, blue: 0.9647058823529412, alpha: 1), end: UIColor(red: 0.7529411764705882, green: 0.5176470588235295, blue: 0.9882352941176471, alpha: 1), angle: 135.0)
        public static let sky = GradientValues(start: UIColor(red: 0.054901960784313725, green: 0.6470588235294118, blue: 0.9137254901960784, alpha: 1), end: UIColor(red: 0.49019607843137253, green: 0.8274509803921568, blue: 0.9882352941176471, alpha: 1), angle: 135.0)
    }

}

public struct ShadowValues: Sendable {
    public let opacity: CGFloat
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let radius: CGFloat
}

public struct AnimationValues: Sendable {
    public let duration: TimeInterval
    public let damping: CGFloat
    public let velocity: CGFloat

    public init(duration: TimeInterval, damping: CGFloat = 1.0, velocity: CGFloat = 0.5) {
        self.duration = duration
        self.damping = damping
        self.velocity = velocity
    }
}

public struct GradientValues: Sendable {
    public let start: UIColor
    public let end: UIColor
    public let angle: CGFloat
}
