import UIKit

// ============================================================
// AUTO-GENERATED by tools/sync-design-tokens.swift
// DO NOT EDIT — changes will be overwritten on next sync.
// Source: docs/design-tokens.json
// Generated: 2026-05-22T09:27:45Z
// ============================================================

public enum ThemeTokens {

    // DEPRECATED: Use ThemeTokens.Color instead (auto-adapts to Dark Mode)
    public enum Colors {
        public enum Light {
            public static let background = UIColor(red: 0.9490196078431372, green: 0.9490196078431372, blue: 0.9686274509803922, alpha: 1)
            public static let badgeBackground = UIColor(red: 0.9490196078431372, green: 0.9490196078431372, blue: 0.9686274509803922, alpha: 1)
            public static let badgeText = UIColor(red: 0.38823529411764707, green: 0.38823529411764707, blue: 0.4, alpha: 1)
            public static let border = UIColor(red: 0.7764705882352941, green: 0.7764705882352941, blue: 0.7843137254901961, alpha: 1)
            public static let cardBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let error = UIColor(red: 1.0, green: 0.23137254901960785, blue: 0.18823529411764706, alpha: 1)
            public static let errorSoft = UIColor(red: 1.0, green: 0.9, blue: 0.9, alpha: 1)
            public static let fabBackground = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let gradientEnd = UIColor(red: 0.6, green: 0.30196078431372547, blue: 0.7490196078431373, alpha: 0.85)
            public static let gradientStart = UIColor(red: 0.25098039215686274, green: 0.45098039215686275, blue: 0.9490196078431372, alpha: 0.85)
            public static let info = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let infoSoft = UIColor(red: 0.9, green: 0.95, blue: 1.0, alpha: 1)
            public static let navigationBarBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let offline = UIColor(red: 0.4, green: 0.45, blue: 0.55, alpha: 1)
            public static let offlineSoft = UIColor(red: 0.93, green: 0.95, blue: 0.96, alpha: 1)
            public static let overlay = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.4)
            public static let placeholder = UIColor(red: 0.78, green: 0.78, blue: 0.8, alpha: 1)
            public static let primary = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let primaryPressed = UIColor(red: 0.0, green: 0.38, blue: 0.85, alpha: 1)
            public static let primarySoft = UIColor(red: 0.9176470588235294, green: 0.9450980392156862, blue: 1.0, alpha: 1)
            public static let secondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let separator = UIColor(red: 0.7764705882352941, green: 0.7764705882352941, blue: 0.7843137254901961, alpha: 1)
            public static let shadow = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.1)
            public static let success = UIColor(red: 0.20392156862745098, green: 0.7803921568627451, blue: 0.34901960784313724, alpha: 1)
            public static let successSoft = UIColor(red: 0.92, green: 0.97, blue: 0.94, alpha: 1)
            public static let surface = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let surfaceElevated = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let tabBarBackground = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let text = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let textSecondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let textTertiary = UIColor(red: 0.7803921568627451, green: 0.7803921568627451, blue: 0.8, alpha: 1)
            public static let unreadDot = UIColor(red: 0.0, green: 0.47843137254901963, blue: 1.0, alpha: 1)
            public static let warning = UIColor(red: 1.0, green: 0.5843137254901961, blue: 0.0, alpha: 1)
            public static let warningSoft = UIColor(red: 1.0, green: 0.96, blue: 0.9, alpha: 1)
        }

        public enum Dark {
            public static let background = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let badgeBackground = UIColor(red: 0.2, green: 0.2, blue: 0.25098039215686274, alpha: 1)
            public static let badgeText = UIColor(red: 0.9215686274509803, green: 0.9215686274509803, blue: 0.9607843137254902, alpha: 1)
            public static let border = UIColor(red: 0.2196078431372549, green: 0.2196078431372549, blue: 0.22745098039215686, alpha: 1)
            public static let cardBackground = UIColor(red: 0.14901960784313725, green: 0.14901960784313725, blue: 0.16862745098039217, alpha: 1)
            public static let error = UIColor(red: 1.0, green: 0.27058823529411763, blue: 0.22745098039215686, alpha: 1)
            public static let errorSoft = UIColor(red: 1.0, green: 0.27058823529411763, blue: 0.22745098039215686, alpha: 0.14)
            public static let fabBackground = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let gradientEnd = UIColor(red: 0.4, green: 0.2, blue: 0.5019607843137255, alpha: 0.9)
            public static let gradientStart = UIColor(red: 0.2, green: 0.30196078431372547, blue: 0.6, alpha: 0.9)
            public static let info = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let infoSoft = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 0.13)
            public static let navigationBarBackground = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let offline = UIColor(red: 0.58, green: 0.64, blue: 0.72, alpha: 1)
            public static let offlineSoft = UIColor(red: 0.58, green: 0.64, blue: 0.72, alpha: 0.13)
            public static let overlay = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.6)
            public static let placeholder = UIColor(red: 0.4, green: 0.44, blue: 0.52, alpha: 1)
            public static let primary = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let primaryPressed = UIColor(red: 0.23, green: 0.51, blue: 0.96, alpha: 1)
            public static let primarySoft = UIColor(red: 0.3764705882352941, green: 0.6470588235294118, blue: 0.9803921568627451, alpha: 0.14)
            public static let secondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let separator = UIColor(red: 0.2196078431372549, green: 0.2196078431372549, blue: 0.22745098039215686, alpha: 1)
            public static let shadow = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.3)
            public static let success = UIColor(red: 0.18823529411764706, green: 0.8196078431372549, blue: 0.34509803921568627, alpha: 1)
            public static let successSoft = UIColor(red: 0.18823529411764706, green: 0.8196078431372549, blue: 0.34509803921568627, alpha: 0.13)
            public static let surface = UIColor(red: 0.10980392156862745, green: 0.10980392156862745, blue: 0.11764705882352941, alpha: 1)
            public static let surfaceElevated = UIColor(red: 0.15, green: 0.15, blue: 0.17, alpha: 1)
            public static let tabBarBackground = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)
            public static let text = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)
            public static let textSecondary = UIColor(red: 0.5568627450980392, green: 0.5568627450980392, blue: 0.5764705882352941, alpha: 1)
            public static let textTertiary = UIColor(red: 0.2823529411764706, green: 0.2823529411764706, blue: 0.2901960784313726, alpha: 1)
            public static let unreadDot = UIColor(red: 0.0392156862745098, green: 0.5176470588235295, blue: 1.0, alpha: 1)
            public static let warning = UIColor(red: 1.0, green: 0.6235294117647059, blue: 0.0392156862745098, alpha: 1)
            public static let warningSoft = UIColor(red: 1.0, green: 0.6235294117647059, blue: 0.0392156862745098, alpha: 0.14)
        }
    }

    public enum Color {
        public static var background: UIColor { dynamicColor(light: Colors.Light.background, dark: Colors.Dark.background) }
        public static var badgeBackground: UIColor { dynamicColor(light: Colors.Light.badgeBackground, dark: Colors.Dark.badgeBackground) }
        public static var badgeText: UIColor { dynamicColor(light: Colors.Light.badgeText, dark: Colors.Dark.badgeText) }
        public static var border: UIColor { dynamicColor(light: Colors.Light.border, dark: Colors.Dark.border) }
        public static var cardBackground: UIColor { dynamicColor(light: Colors.Light.cardBackground, dark: Colors.Dark.cardBackground) }
        public static var error: UIColor { dynamicColor(light: Colors.Light.error, dark: Colors.Dark.error) }
        public static var errorSoft: UIColor { dynamicColor(light: Colors.Light.errorSoft, dark: Colors.Dark.errorSoft) }
        public static var fabBackground: UIColor { dynamicColor(light: Colors.Light.fabBackground, dark: Colors.Dark.fabBackground) }
        public static var gradientEnd: UIColor { dynamicColor(light: Colors.Light.gradientEnd, dark: Colors.Dark.gradientEnd) }
        public static var gradientStart: UIColor { dynamicColor(light: Colors.Light.gradientStart, dark: Colors.Dark.gradientStart) }
        public static var info: UIColor { dynamicColor(light: Colors.Light.info, dark: Colors.Dark.info) }
        public static var infoSoft: UIColor { dynamicColor(light: Colors.Light.infoSoft, dark: Colors.Dark.infoSoft) }
        public static var navigationBarBackground: UIColor { dynamicColor(light: Colors.Light.navigationBarBackground, dark: Colors.Dark.navigationBarBackground) }
        public static var offline: UIColor { dynamicColor(light: Colors.Light.offline, dark: Colors.Dark.offline) }
        public static var offlineSoft: UIColor { dynamicColor(light: Colors.Light.offlineSoft, dark: Colors.Dark.offlineSoft) }
        public static var overlay: UIColor { dynamicColor(light: Colors.Light.overlay, dark: Colors.Dark.overlay) }
        public static var placeholder: UIColor { dynamicColor(light: Colors.Light.placeholder, dark: Colors.Dark.placeholder) }
        public static var primary: UIColor { dynamicColor(light: Colors.Light.primary, dark: Colors.Dark.primary) }
        public static var primaryPressed: UIColor { dynamicColor(light: Colors.Light.primaryPressed, dark: Colors.Dark.primaryPressed) }
        public static var primarySoft: UIColor { dynamicColor(light: Colors.Light.primarySoft, dark: Colors.Dark.primarySoft) }
        public static var secondary: UIColor { dynamicColor(light: Colors.Light.secondary, dark: Colors.Dark.secondary) }
        public static var separator: UIColor { dynamicColor(light: Colors.Light.separator, dark: Colors.Dark.separator) }
        public static var shadow: UIColor { dynamicColor(light: Colors.Light.shadow, dark: Colors.Dark.shadow) }
        public static var success: UIColor { dynamicColor(light: Colors.Light.success, dark: Colors.Dark.success) }
        public static var successSoft: UIColor { dynamicColor(light: Colors.Light.successSoft, dark: Colors.Dark.successSoft) }
        public static var surface: UIColor { dynamicColor(light: Colors.Light.surface, dark: Colors.Dark.surface) }
        public static var surfaceElevated: UIColor { dynamicColor(light: Colors.Light.surfaceElevated, dark: Colors.Dark.surfaceElevated) }
        public static var tabBarBackground: UIColor { dynamicColor(light: Colors.Light.tabBarBackground, dark: Colors.Dark.tabBarBackground) }
        public static var text: UIColor { dynamicColor(light: Colors.Light.text, dark: Colors.Dark.text) }
        public static var textSecondary: UIColor { dynamicColor(light: Colors.Light.textSecondary, dark: Colors.Dark.textSecondary) }
        public static var textTertiary: UIColor { dynamicColor(light: Colors.Light.textTertiary, dark: Colors.Dark.textTertiary) }
        public static var unreadDot: UIColor { dynamicColor(light: Colors.Light.unreadDot, dark: Colors.Dark.unreadDot) }
        public static var warning: UIColor { dynamicColor(light: Colors.Light.warning, dark: Colors.Dark.warning) }
        public static var warningSoft: UIColor { dynamicColor(light: Colors.Light.warningSoft, dark: Colors.Dark.warningSoft) }

        public static var divider: UIColor { separator }
        public static var navigationBarTitle: UIColor { text }
        public static var iconBackground: UIColor { primary.withAlphaComponent(0.1) }
        public static var dimOverlay: UIColor { overlay }
        public static var textOnColor: UIColor { dynamicColor(light: .white, dark: .white) }
        public static var onPrimary: UIColor { textOnColor }
        public static var scrim: UIColor { overlay }
        public static var overlayStrong: UIColor { dynamicColor(light: UIColor(red: 0.067, green: 0.094, blue: 0.153, alpha: 0.7), dark: UIColor(red: 0, green: 0, blue: 0, alpha: 0.8)) }
        public static var overlaySoft: UIColor { dynamicColor(light: UIColor(red: 0.067, green: 0.094, blue: 0.153, alpha: 0.2), dark: UIColor(red: 0, green: 0, blue: 0, alpha: 0.3)) }
        public static var accent: UIColor { dynamicColor(light: UIColor(red: 0.486, green: 0.227, blue: 0.929, alpha: 1), dark: UIColor(red: 0.655, green: 0.545, blue: 0.98, alpha: 1)) }

        private static func dynamicColor(light: UIColor, dark: UIColor) -> UIColor {
            UIColor { trait in
                trait.userInterfaceStyle == .dark ? dark : light
            }
        }
    }

    public enum Typography {
        public static let body = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 17, weight: .regular))
        public static let button = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 15, weight: .semibold))
        public static let buttonMedium = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 15, weight: .medium))
        public static let caption = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 13, weight: .regular))
        public static let caption1 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 12, weight: .regular))
        public static let caption2 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 11, weight: .regular))
        public static let cardTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 16, weight: .semibold))
        public static let callout = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 16, weight: .regular))
        public static let footnote = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 13, weight: .regular))
        public static let headline = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 17, weight: .semibold))
        public static let largeTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let metadata = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 12, weight: .regular))
        public static let rowTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 15, weight: .medium))
        public static let sectionTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 17, weight: .semibold))
        public static let subheadline = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 15, weight: .regular))
        public static let badge = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 10, weight: .bold))
        public static let tabLabel = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 11, weight: .medium))
        public static let screenTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let compactTitle = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 24, weight: .bold))
        public static let monospaceBody = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 13, weight: .regular))
        public static let monospaceSmall = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 11, weight: .regular))
        public static let monospaceMini = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 10, weight: .regular))
        public static let monospaceTitle = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 18, weight: .bold))
        public static let monospaceDisplay = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 20, weight: .bold))
        public static let monospaceLargeMedium = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 14, weight: .medium))
        public static let monospaceLargeSemibold = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 17, weight: .semibold))
        public static let monospaceMeta = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 12, weight: .regular))
        public static let monospaceMetaBold = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 12, weight: .bold))
        public static let monospaceMiniMedium = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 10, weight: .medium))
        public static let monospaceSmallMedium = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 11, weight: .medium))
        public static let monospaceMicro = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 9, weight: .regular))
        public static let monospaceLarge = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 14, weight: .regular))
        public static let monospaceBodyMedium = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 13, weight: .medium))
        public static let monospaceDisplaySemibold = UIFontMetrics.default.scaledFont(for: UIFont.monospacedSystemFont(ofSize: 20, weight: .semibold))
        public static let title1 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 28, weight: .bold))
        public static let title2 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 22, weight: .bold))
        public static let title3 = UIFontMetrics.default.scaledFont(for: .systemFont(ofSize: 20, weight: .semibold))
    }

    public enum Spacing {
        public static let lg: CGFloat = 24.0
        public static let md: CGFloat = 16.0
        public static let sm: CGFloat = 8.0
        public static let xl: CGFloat = 32.0
        public static let xs: CGFloat = 4.0
        public static let xxs: CGFloat = 2.0
        public static let xxl: CGFloat = 48.0
        public static let screenTop: CGFloat = 12.0
        public static let screenBottom: CGFloat = 24.0
        public static let screenHorizontal: CGFloat = 16.0
        public static let section: CGFloat = 32.0
    }

    public enum CornerRadius {
        public static let full: CGFloat = 999.0
        public static let lg: CGFloat = 12.0
        public static let md: CGFloat = 8.0
        public static let sm: CGFloat = 4.0
        public static let xl: CGFloat = 16.0
        public static let xs: CGFloat = 2.0
        public static let xxl: CGFloat = 20.0
        public static let avatar: CGFloat = 22.0
        public static let pill: CGFloat = 28.0
        public static let card: CGFloat = 12.0
        public static let row: CGFloat = 10.0
    }

    public enum Shadows {
        public static let Card = ShadowValues(opacity: 0.08, offsetX: 0.0, offsetY: 4.0, radius: 12.0)
        public static let SearchBar = ShadowValues(opacity: 0.06, offsetX: 0.0, offsetY: 2.0, radius: 8.0)
        public static let Fab = ShadowValues(opacity: 0.3, offsetX: 0.0, offsetY: 4.0, radius: 8.0)
        public static let Modal = ShadowValues(opacity: 0.15, offsetX: 0.0, offsetY: 8.0, radius: 24.0)
        public static let NavBar = ShadowValues(opacity: 0.03, offsetX: 0.0, offsetY: 2.0, radius: 8.0)
        public static let Tooltip = ShadowValues(opacity: 0.12, offsetX: 0.0, offsetY: 2.0, radius: 4.0)
        public static let card = ShadowValues(opacity: 0.08, offsetX: 0.0, offsetY: 4.0, radius: 12.0)
        public static let floatingAction = ShadowValues(opacity: 0.3, offsetX: 0.0, offsetY: 8.0, radius: 18.0)
    }

    public enum Opacity {
        public static let badge: CGFloat = 0.12
        public static let disabled: CGFloat = 0.3
        public static let hover: CGFloat = 0.8
        public static let overlay: CGFloat = 0.4
        public static let placeholder: CGFloat = 0.4
        public static let pressed: CGFloat = 0.6
        public static let badgeFill: CGFloat = 0.14
    }

    public enum Animation {
        public static let fast = AnimationValues(duration: 0.15)
        public static let modal = AnimationValues(duration: 0.5)
        public static let normal = AnimationValues(duration: 0.25)
        public static let slow = AnimationValues(duration: 0.35)
        public static let spring = AnimationValues(duration: 0.3, damping: 0.8)
    }

    public enum Icons {
        public enum Sizes {
            public static let lg: CGFloat = 24.0
            public static let md: CGFloat = 20.0
            public static let sm: CGFloat = 16.0
            public static let xl: CGFloat = 32.0
            public static let xs: CGFloat = 12.0
            public static let xxl: CGFloat = 48.0
            public static let tab: CGFloat = 23.0
        }
    }

    public enum Breakpoints {
        public static let compact: CGFloat = 320.0
        public static let large: CGFloat = 428.0
        public static let regular: CGFloat = 375.0
    }

    public enum ComponentContract {
        public enum ResourceCard {
            public static let minHeight: CGFloat = 80
            public static let maxHeight: CGFloat = 140
            public static let iconSize: CGFloat = 22
            public static let titleMaxLines: CGFloat = 2
            public static let metadataMaxLines: CGFloat = 1
        }
        public enum MessageCell {
            public static let minHeight: CGFloat = 72
            public static let maxHeight: CGFloat = 96
            public static let titleMaxLines: CGFloat = 1
            public static let bodyMaxLines: CGFloat = 2
        }
        public enum FilterPill {
            public static let height: CGFloat = 32
            public static let minWidth: CGFloat = 56
            public static let horizontalPadding: CGFloat = 14
        }
        public enum SearchField {
            public static let height: CGFloat = 42
            public static let cornerRadius: CGFloat = 10
            public static let horizontalPadding: CGFloat = 12
            public static let iconSize: CGFloat = 18
        }
        public enum SettingsRow {
            public static let minHeight: CGFloat = 52
            public static let maxHeight: CGFloat = 60
            public static let iconBox: CGFloat = 32
            public static let iconSize: CGFloat = 20
            public static let chevronSize: CGFloat = 16
            public static let horizontalPadding: CGFloat = 16
            public static let titleMaxLines: CGFloat = 1
        }
        public enum ActionTile {
            public static let height: CGFloat = 72
            public static let iconSize: CGFloat = 22
            public static let minWidth: CGFloat = 72
            public static let titleMaxLines: CGFloat = 1
        }
        public enum EmptyState {
            public static let iconSize: CGFloat = 48
            public static let maxWidth: CGFloat = 280
            public static let titleSize: CGFloat = 17
            public static let bodySize: CGFloat = 13
            public static let requiresPrimaryAction: Bool = true
        }
        public enum TapTarget {
            public static let minimumWidth: CGFloat = 44
            public static let minimumHeight: CGFloat = 44
        }
        public enum TabBar {
            public static let height: CGFloat = 56
            public static let iconSize: CGFloat = 23
            public static let labelSize: CGFloat = 11
            public static let contentTopPadding: CGFloat = 6
            public static let mustNotOverlapScrollContent: Bool = true
        }
    }
}

public struct ShadowValues: Sendable {
    public let opacity: CGFloat
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let radius: CGFloat
}

public struct AnimationValues: Sendable {
    public let duration: TimeInterval
    public let damping: CGFloat

    public init(duration: TimeInterval, damping: CGFloat = 1.0) {
        self.duration = duration
        self.damping = damping
    }
}
