import Foundation

func generateCSS(_ tokens: DesignTokens) -> String {
    var lines: [String] = []
    lines.append("/*")
    lines.append(" * AUTO-GENERATED by tools/sync-design-tokens.swift")
    lines.append(" * DO NOT EDIT — changes will be overwritten on next sync.")
    lines.append(" * Source: docs/design-tokens.json")
    lines.append(" */")
    lines.append("")

    lines.append(":root {")
    let lightKeys = tokens.colors.light.keys.sorted()
    for key in lightKeys {
        lines.append("  --color-\(key): \(cssColor(tokens.colors.light[key]!));")
    }
    lines.append("")
    let spacingKeys = tokens.spacing.keys.sorted()
    for key in spacingKeys {
        lines.append("  --spacing-\(key): \(Int(tokens.spacing[key]!))px;")
    }
    lines.append("")
    let radiusKeys = tokens.cornerRadius.keys.sorted()
    for key in radiusKeys {
        lines.append("  --radius-\(key): \(Int(tokens.cornerRadius[key]!))px;")
    }
    lines.append("")
    let typoKeys = tokens.typography.keys.sorted()
    for key in typoKeys {
        let t = tokens.typography[key]!
        lines.append("  --font-\(key)-size: \(Int(t.size))px;")
        lines.append("  --font-\(key)-weight: \(t.weight);")
    }
    lines.append("")
    let opacityKeys = tokens.opacity.keys.sorted()
    for key in opacityKeys {
        lines.append("  --opacity-\(key): \(tokens.opacity[key]!);")
    }
    lines.append("")
    let shadowKeys = tokens.shadows.elevation.keys.sorted()
    for key in shadowKeys {
        let s = tokens.shadows.elevation[key]!
        lines.append("  --shadow-\(key): 0 \(Int(s.offsetY))px \(Int(s.radius))px rgba(0,0,0,\(s.opacity.lightValue));")
    }
    lines.append("")
    let iconKeys = tokens.icon.keys.sorted()
    for key in iconKeys {
        let val = tokens.icon[key]!
        lines.append("  --icon-\(key): \(Int(val))px;")
    }
    lines.append("")
    if let contracts = tokens.componentContracts {
        let contractKeys = contracts.keys.sorted()
        for contractName in contractKeys {
            let props = contracts[contractName]!
            let propKeys = props.keys.sorted()
            for propKey in propKeys {
                let val = props[propKey]!
                let cssVal = val.cssLiteral
                if !cssVal.isEmpty {
                    lines.append("  --contract-\(contractName)-\(propKey): \(cssVal);")
                }
            }
        }
    }
    lines.append("")
    if let gradients = tokens.gradients {
        let gradientKeys = gradients.keys.sorted()
        for key in gradientKeys {
            let g = gradients[key]!
            lines.append("  --gradient-\(key): linear-gradient(\(Int(g.angle))deg, \(cssColor(g.start)), \(cssColor(g.end)));")
            lines.append("  --gradient-\(key)-start: \(cssColor(g.start));")
            lines.append("  --gradient-\(key)-end: \(cssColor(g.end));")
        }
    }
    lines.append("}")
    lines.append("")

    lines.append("@media (prefers-color-scheme: dark) {")
    lines.append("  :root {")
    let darkKeys = tokens.colors.dark.keys.sorted()
    for key in darkKeys {
        lines.append("    --color-\(key): \(cssColor(tokens.colors.dark[key]!));")
    }
    lines.append("  }")
    lines.append("}")
    lines.append("")

    lines.append("[data-theme=\"dark\"] {")
    for key in darkKeys {
        lines.append("  --color-\(key): \(cssColor(tokens.colors.dark[key]!));")
    }
    lines.append("}")

    return lines.joined(separator: "\n") + "\n"
}
