import Foundation

func camelToSnake(_ s: String) -> String {
    s.replacingOccurrences(of: "([A-Z])", with: "_$1", options: .regularExpression)
        .lowercased()
        .replacingOccurrences(of: "__", with: "_")
}

func hexToAndroidLong(_ hex: String) -> String? {
    guard let c = parseHex(hex) else { return nil }
    let a = Int(c.a * 255)
    let r = Int(c.r * 255)
    let g = Int(c.g * 255)
    let b = Int(c.b * 255)
    return String(format: "0x%02X%02X%02X%02X", a, r, g, b)
}

func hexToXmlColor(_ hex: String) -> String? {
    guard let c = parseHex(hex) else { return nil }
    let a = Int(c.a * 255)
    let r = Int(c.r * 255)
    let g = Int(c.g * 255)
    let b = Int(c.b * 255)
    return String(format: "#%02X%02X%02X%02X", a, r, g, b)
}

func kotlinColorExpr(_ hex: String) -> String {
    guard let c = parseHex(hex) else { return "Color(0xFF000000) /* PARSE ERROR: \(hex) */" }
    let a = Int(c.a * 255)
    let r = Int(c.r * 255)
    let g = Int(c.g * 255)
    let b = Int(c.b * 255)
    return String(format: "Color(0x%02X%02X%02X%02X)", a, r, g, b)
}

func weightToKotlin(_ w: String) -> String {
    switch w {
    case "light": return "FontWeight.Light"
    case "regular": return "FontWeight.Normal"
    case "medium": return "FontWeight.Medium"
    case "semibold": return "FontWeight.SemiBold"
    case "bold": return "FontWeight.Bold"
    default: return "FontWeight.Normal"
    }
}

func generateKotlin(_ tokens: DesignTokens) -> String {
    var lines: [String] = []
    lines.append("// ============================================================")
    lines.append("// AUTO-GENERATED by tools/sync-design-tokens.swift")
    lines.append("// DO NOT EDIT — changes will be overwritten on next sync.")
    lines.append("// Source: docs/design-tokens.json")
    lines.append("// ============================================================")
    lines.append("")
    lines.append("package com.webbridgekit.design")
    lines.append("")
    lines.append("import androidx.compose.ui.graphics.Color")
    lines.append("import androidx.compose.ui.unit.dp")
    lines.append("import androidx.compose.ui.unit.sp")
    lines.append("import androidx.compose.ui.text.font.FontWeight")
    lines.append("import androidx.compose.ui.text.TextStyle")
    lines.append("")
    lines.append("object ThemeTokens {")
    lines.append("")

    lines.append("    object Color {")
    let lightKeys = tokens.colors.light.keys.sorted()
    for key in lightKeys {
        let val = tokens.colors.light[key]!
        lines.append("        val \(key)Light = \(kotlinColorExpr(val))")
    }
    lines.append("")
    let darkKeys = tokens.colors.dark.keys.sorted()
    for key in darkKeys {
        let val = tokens.colors.dark[key]!
        lines.append("        val \(key)Dark = \(kotlinColorExpr(val))")
    }
    lines.append("")
    lines.append("        // Dynamic colors (use with isSystemInDarkTheme())")
    let colorKeys = lightKeys.filter { tokens.colors.dark[$0] != nil }
    for key in colorKeys {
        lines.append("        val \(key) @Composable get() = if (isSystemInDarkTheme()) \(key)Dark else \(key)Light")
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object Spacing {")
    let spacingKeys = tokens.spacing.keys.sorted()
    for key in spacingKeys {
        let val = tokens.spacing[key]!
        let intVal = Int(val)
        if val == Double(intVal) {
            lines.append("        val \(key) = \(intVal).dp")
        } else {
            lines.append("        val \(key) = \(val).dp")
        }
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object CornerRadius {")
    let radiusKeys = tokens.cornerRadius.keys.sorted()
    for key in radiusKeys {
        let val = tokens.cornerRadius[key]!
        let intVal = Int(val)
        if val == Double(intVal) && intVal < 999 {
            lines.append("        val \(key) = \(intVal).dp")
        } else if intVal >= 999 {
            lines.append("        val \(key) = 50.dp // full radius")
        } else {
            lines.append("        val \(key) = \(val).dp")
        }
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object Typography {")
    let typoKeys = tokens.typography.keys.sorted()
    for key in typoKeys {
        let t = tokens.typography[key]!
        let size = Int(t.size)
        let w = weightToKotlin(t.weight)
        lines.append("        val \(key) = TextStyle(")
        lines.append("            fontSize = \(size).sp,")
        lines.append("            fontWeight = \(w)")
        lines.append("        )")
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object Shadows {")
    let shadowKeys = tokens.shadows.elevation.keys.sorted()
    for key in shadowKeys {
        let s = tokens.shadows.elevation[key]!
        lines.append("        val \(key) = ShadowValues(")
        lines.append("            offsetY = \(Int(s.offsetY)).dp,")
        lines.append("            blur = \(Int(s.radius)).dp,")
        lines.append("            opacity = \(s.opacity.lightValue)f")
        lines.append("        )")
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object Opacity {")
    let opacityKeys = tokens.opacity.keys.sorted()
    for key in opacityKeys {
        let val = tokens.opacity[key]!
        lines.append("        val \(key) = \(val)f")
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object Animation {")
    let animKeys = tokens.animation.keys.sorted()
    for key in animKeys {
        let a = tokens.animation[key]!
        var params: [String] = ["duration = \(a.duration)f"]
        if let d = a.damping { params.append("damping = \(d)f") }
        if let v = a.velocity { params.append("velocity = \(v)f") }
        lines.append("        val \(key) = AnimationValues(\(params.joined(separator: ", ")))")
    }
    lines.append("    }")
    lines.append("")

    lines.append("    object IconSize {")
    let iconKeys = tokens.icon.keys.sorted()
    for key in iconKeys {
        let val = tokens.icon[key]!
        let intVal = Int(val)
        lines.append("        val \(key) = \(intVal).dp")
    }
    lines.append("    }")
    lines.append("")

    if let breakpoints = tokens.breakpoints {
        lines.append("    object Breakpoints {")
        let bpKeys = breakpoints.keys.sorted()
        for key in bpKeys {
            let val = breakpoints[key]!
            lines.append("        val \(key) = \(Int(val)).dp")
        }
        lines.append("    }")
        lines.append("")
    }

    if let gradients = tokens.gradients, !gradients.isEmpty {
        lines.append("    object Gradients {")
        let gradientKeys = gradients.keys.sorted()
        for key in gradientKeys {
            let g = gradients[key]!
            lines.append("        val \(key) = GradientValues(")
            lines.append("            start = \(kotlinColorExpr(g.start)),")
            lines.append("            end = \(kotlinColorExpr(g.end)),")
            lines.append("            angle = \(Int(g.angle)).toFloat()")
            lines.append("        )")
        }
        lines.append("    }")
        lines.append("")
    }

    lines.append("}")
    lines.append("")
    lines.append("data class ShadowValues(")
    lines.append("    val offsetY: Dp,")
    lines.append("    val blur: Dp,")
    lines.append("    val opacity: Float")
    lines.append(")")
    lines.append("")
    lines.append("data class AnimationValues(")
    lines.append("    val duration: Float,")
    lines.append("    val damping: Float = 1.0f,")
    lines.append("    val velocity: Float = 0.5f")
    lines.append(")")
    lines.append("")
    lines.append("data class GradientValues(")
    lines.append("    val start: Color,")
    lines.append("    val end: Color,")
    lines.append("    val angle: Float")
    lines.append(")")
    lines.append("")

    return lines.joined(separator: "\n")
}

func generateAndroidXML(_ tokens: DesignTokens) -> [String: String] {
    var result: [String: String] = [:]

    // colors_tokens.xml (light)
    var lightColors = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    lightColors += "<!-- AUTO-GENERATED by tools/sync-design-tokens.swift -->\n"
    lightColors += "<resources>\n"
    for key in tokens.colors.light.keys.sorted() {
        if let xmlColor = hexToXmlColor(tokens.colors.light[key]!) {
            let name = camelToSnake(key)
            lightColors += "    <color name=\"\(name)\">\(xmlColor)</color>\n"
        }
    }
    lightColors += "</resources>\n"
    result["values/colors_tokens.xml"] = lightColors

    // colors_tokens.xml (dark / values-night)
    var darkColors = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    darkColors += "<!-- AUTO-GENERATED by tools/sync-design-tokens.swift -->\n"
    darkColors += "<resources>\n"
    for key in tokens.colors.dark.keys.sorted() {
        if let xmlColor = hexToXmlColor(tokens.colors.dark[key]!) {
            let name = camelToSnake(key)
            darkColors += "    <color name=\"\(name)\">\(xmlColor)</color>\n"
        }
    }
    darkColors += "</resources>\n"
    result["values-night/colors_tokens.xml"] = darkColors

    // dimens_tokens.xml
    var dimens = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    dimens += "<!-- AUTO-GENERATED by tools/sync-design-tokens.swift -->\n"
    dimens += "<resources>\n"
    dimens += "    <!-- Spacing -->\n"
    for key in tokens.spacing.keys.sorted() {
        let val = tokens.spacing[key]!
        let intVal = Int(val)
        dimens += "    <dimen name=\"spacing_\(camelToSnake(key))\">\(intVal)dp</dimen>\n"
    }
    dimens += "\n"
    dimens += "    <!-- Corner Radius -->\n"
    for key in tokens.cornerRadius.keys.sorted() {
        let val = tokens.cornerRadius[key]!
        let intVal = Int(val)
        if intVal < 999 {
            dimens += "    <dimen name=\"corner_radius_\(camelToSnake(key))\">\(intVal)dp</dimen>\n"
        } else {
            dimens += "    <dimen name=\"corner_radius_\(camelToSnake(key))\">50dp</dimen>\n"
        }
    }
    dimens += "\n"
    dimens += "    <!-- Icon Sizes -->\n"
    for key in tokens.icon.keys.sorted() {
        let val = tokens.icon[key]!
        let intVal = Int(val)
        dimens += "    <dimen name=\"icon_\(camelToSnake(key))\">\(intVal)dp</dimen>\n"
    }
    dimens += "</resources>\n"
    result["values/dimens_tokens.xml"] = dimens

    return result
}
