// ============================================================
// AUTO-GENERATED by tools/sync-design-tokens.swift
// DO NOT EDIT — changes will be overwritten on next sync.
// Source: docs/design-tokens.json
// ============================================================

package com.webbridgekit.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.TextStyle

object ThemeTokens {

    object Color {
        val accentLight = Color(0xFF8B5CF6)
        val accentSoftLight = Color(0xFFF3EFFE)
        val backgroundLight = Color(0xFFF8F9FC)
        val backgroundSecondaryLight = Color(0xFFF0F2F7)
        val backgroundTertiaryLight = Color(0xFFE8EBF2)
        val borderLight = Color(0xFFD8DEE8)
        val cardBackgroundLight = Color(0xFFFFFFFF)
        val errorLight = Color(0xFFDC2626)
        val errorSoftLight = Color(0xFFFEECEC)
        val infoLight = Color(0xFF0F766E)
        val infoSoftLight = Color(0xFFE7F6F4)
        val navigationBarBackgroundLight = Color(0xFFFFFFFF)
        val offlineLight = Color(0xFF64748B)
        val offlineSoftLight = Color(0xFFEEF2F6)
        val overlayLight = Color(0x6B111827)
        val placeholderLight = Color(0xFFA5ADBA)
        val primaryLight = Color(0xFF4F6AF6)
        val primaryPressedLight = Color(0xFF3D56E0)
        val primarySoftLight = Color(0xFFEEF1FE)
        val separatorLight = Color(0xFFE6EAF0)
        val shadowLight = Color(0x19111827)
        val successLight = Color(0xFF16A34A)
        val successSoftLight = Color(0xFFEAF8EF)
        val surfaceLight = Color(0xFFFFFFFF)
        val surfaceElevatedLight = Color(0xFFFFFFFF)
        val tabBarBackgroundLight = Color(0xFFFFFFFF)
        val textLight = Color(0xFF1A1D2E)
        val textSecondaryLight = Color(0xFF6B7394)
        val textTertiaryLight = Color(0xFF9CA3C4)
        val warningLight = Color(0xFFD97706)
        val warningSoftLight = Color(0xFFFFF4E5)

        val accentDark = Color(0xFFA78BFA)
        val accentSoftDark = Color(0x23A78BFA)
        val backgroundDark = Color(0xFF0F1117)
        val backgroundSecondaryDark = Color(0xFF1A1D28)
        val backgroundTertiaryDark = Color(0xFF252A38)
        val borderDark = Color(0xFF2A323D)
        val cardBackgroundDark = Color(0xFF1E2233)
        val errorDark = Color(0xFFF87171)
        val errorSoftDark = Color(0x23F87171)
        val infoDark = Color(0xFF2DD4BF)
        val infoSoftDark = Color(0x212DD4BF)
        val navigationBarBackgroundDark = Color(0xFF0F1117)
        val offlineDark = Color(0xFF94A3B8)
        val offlineSoftDark = Color(0x2194A3B8)
        val overlayDark = Color(0x93000000)
        val placeholderDark = Color(0xFF667085)
        val primaryDark = Color(0xFF6B82F8)
        val primaryPressedDark = Color(0xFF4F6AF6)
        val primarySoftDark = Color(0x236B82F8)
        val separatorDark = Color(0xFF232A34)
        val shadowDark = Color(0x4C000000)
        val successDark = Color(0xFF4ADE80)
        val successSoftDark = Color(0x214ADE80)
        val surfaceDark = Color(0xFF13171D)
        val surfaceElevatedDark = Color(0xFF191E26)
        val tabBarBackgroundDark = Color(0xFF10141A)
        val textDark = Color(0xFFF0F2F7)
        val textSecondaryDark = Color(0xFF8892B0)
        val textTertiaryDark = Color(0xFF5C6585)
        val warningDark = Color(0xFFFBBF24)
        val warningSoftDark = Color(0x23FBBF24)

        // Dynamic colors (use with isSystemInDarkTheme())
        val accent @Composable get() = if (isSystemInDarkTheme()) accentDark else accentLight
        val accentSoft @Composable get() = if (isSystemInDarkTheme()) accentSoftDark else accentSoftLight
        val background @Composable get() = if (isSystemInDarkTheme()) backgroundDark else backgroundLight
        val backgroundSecondary @Composable get() = if (isSystemInDarkTheme()) backgroundSecondaryDark else backgroundSecondaryLight
        val backgroundTertiary @Composable get() = if (isSystemInDarkTheme()) backgroundTertiaryDark else backgroundTertiaryLight
        val border @Composable get() = if (isSystemInDarkTheme()) borderDark else borderLight
        val cardBackground @Composable get() = if (isSystemInDarkTheme()) cardBackgroundDark else cardBackgroundLight
        val error @Composable get() = if (isSystemInDarkTheme()) errorDark else errorLight
        val errorSoft @Composable get() = if (isSystemInDarkTheme()) errorSoftDark else errorSoftLight
        val info @Composable get() = if (isSystemInDarkTheme()) infoDark else infoLight
        val infoSoft @Composable get() = if (isSystemInDarkTheme()) infoSoftDark else infoSoftLight
        val navigationBarBackground @Composable get() = if (isSystemInDarkTheme()) navigationBarBackgroundDark else navigationBarBackgroundLight
        val offline @Composable get() = if (isSystemInDarkTheme()) offlineDark else offlineLight
        val offlineSoft @Composable get() = if (isSystemInDarkTheme()) offlineSoftDark else offlineSoftLight
        val overlay @Composable get() = if (isSystemInDarkTheme()) overlayDark else overlayLight
        val placeholder @Composable get() = if (isSystemInDarkTheme()) placeholderDark else placeholderLight
        val primary @Composable get() = if (isSystemInDarkTheme()) primaryDark else primaryLight
        val primaryPressed @Composable get() = if (isSystemInDarkTheme()) primaryPressedDark else primaryPressedLight
        val primarySoft @Composable get() = if (isSystemInDarkTheme()) primarySoftDark else primarySoftLight
        val separator @Composable get() = if (isSystemInDarkTheme()) separatorDark else separatorLight
        val shadow @Composable get() = if (isSystemInDarkTheme()) shadowDark else shadowLight
        val success @Composable get() = if (isSystemInDarkTheme()) successDark else successLight
        val successSoft @Composable get() = if (isSystemInDarkTheme()) successSoftDark else successSoftLight
        val surface @Composable get() = if (isSystemInDarkTheme()) surfaceDark else surfaceLight
        val surfaceElevated @Composable get() = if (isSystemInDarkTheme()) surfaceElevatedDark else surfaceElevatedLight
        val tabBarBackground @Composable get() = if (isSystemInDarkTheme()) tabBarBackgroundDark else tabBarBackgroundLight
        val text @Composable get() = if (isSystemInDarkTheme()) textDark else textLight
        val textSecondary @Composable get() = if (isSystemInDarkTheme()) textSecondaryDark else textSecondaryLight
        val textTertiary @Composable get() = if (isSystemInDarkTheme()) textTertiaryDark else textTertiaryLight
        val warning @Composable get() = if (isSystemInDarkTheme()) warningDark else warningLight
        val warningSoft @Composable get() = if (isSystemInDarkTheme()) warningSoftDark else warningSoftLight
    }

    object Spacing {
        val lg = 16.dp
        val md = 12.dp
        val screenBottom = 24.dp
        val screenHorizontal = 16.dp
        val screenTop = 16.dp
        val section = 32.dp
        val sm = 8.dp
        val xl = 20.dp
        val xs = 4.dp
        val xxl = 24.dp
        val xxs = 2.dp
        val xxxl = 32.dp
    }

    object CornerRadius {
        val avatar = 22.dp
        val card = 16.dp
        val full = 50.dp // full radius
        val lg = 12.dp
        val md = 12.dp
        val pill = 28.dp
        val row = 12.dp
        val sheet = 20.dp
        val sm = 8.dp
        val xl = 24.dp
        val xs = 6.dp
        val xxl = 20.dp
    }

    object Typography {
        val badge = TextStyle(
            fontSize = 10.sp,
            fontWeight = FontWeight.Bold
        )
        val body = TextStyle(
            fontSize = 15.sp,
            fontWeight = FontWeight.Normal
        )
        val button = TextStyle(
            fontSize = 15.sp,
            fontWeight = FontWeight.SemiBold
        )
        val buttonMedium = TextStyle(
            fontSize = 15.sp,
            fontWeight = FontWeight.Medium
        )
        val caption = TextStyle(
            fontSize = 12.sp,
            fontWeight = FontWeight.Normal
        )
        val cardTitle = TextStyle(
            fontSize = 16.sp,
            fontWeight = FontWeight.SemiBold
        )
        val compactTitle = TextStyle(
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold
        )
        val display = TextStyle(
            fontSize = 28.sp,
            fontWeight = FontWeight.Bold
        )
        val displayLarge = TextStyle(
            fontSize = 34.sp,
            fontWeight = FontWeight.Bold
        )
        val metadata = TextStyle(
            fontSize = 13.sp,
            fontWeight = FontWeight.Normal
        )
        val monospaceMeta = TextStyle(
            fontSize = 12.sp,
            fontWeight = FontWeight.Normal
        )
        val rowTitle = TextStyle(
            fontSize = 16.sp,
            fontWeight = FontWeight.Medium
        )
        val screenTitle = TextStyle(
            fontSize = 28.sp,
            fontWeight = FontWeight.Bold
        )
        val sectionTitle = TextStyle(
            fontSize = 17.sp,
            fontWeight = FontWeight.SemiBold
        )
        val tabLabel = TextStyle(
            fontSize = 11.sp,
            fontWeight = FontWeight.Medium
        )
    }

    object Shadows {
        val card = ShadowValues(
            offsetY = 4.dp,
            blur = 16.dp,
            opacity = 0.08f
        )
        val floatingAction = ShadowValues(
            offsetY = 8.dp,
            blur = 24.dp,
            opacity = 0.2f
        )
        val lg = ShadowValues(
            offsetY = 8.dp,
            blur = 24.dp,
            opacity = 0.12f
        )
        val md = ShadowValues(
            offsetY = 2.dp,
            blur = 8.dp,
            opacity = 0.1f
        )
        val none = ShadowValues(
            offsetY = 0.dp,
            blur = 0.dp,
            opacity = 0.0f
        )
        val sheet = ShadowValues(
            offsetY = 12.dp,
            blur = 32.dp,
            opacity = 0.15f
        )
        val sm = ShadowValues(
            offsetY = 1.dp,
            blur = 3.dp,
            opacity = 0.08f
        )
    }

    object Opacity {
        val badge = 0.14f
        val badgeFill = 0.14f
        val disabled = 0.36f
        val hover = 0.88f
        val overlay = 0.42f
        val placeholder = 0.36f
        val pressed = 0.72f
        val scrim = 0.42f
        val separator = 0.72f
    }

    object Animation {
        val fast = AnimationValues(duration = 0.15f)
        val modal = AnimationValues(duration = 0.36f, damping = 0.88f)
        val normal = AnimationValues(duration = 0.25f)
        val sheet = AnimationValues(duration = 0.36f, damping = 0.88f)
        val slow = AnimationValues(duration = 0.4f)
        val spring = AnimationValues(duration = 0.5f, damping = 0.85f, velocity = 0.5f)
    }

    object IconSize {
        val chevron = 16.dp
        val empty = 48.dp
        val lg = 24.dp
        val md = 20.dp
        val quickAction = 22.dp
        val settings = 20.dp
        val sm = 16.dp
        val tab = 23.dp
        val xl = 24.dp
        val xs = 14.dp
        val xxl = 48.dp
    }

    object Breakpoints {
        val compact = 320.dp
        val large = 428.dp
        val regular = 375.dp
    }

    object Gradients {
        val blue = GradientValues(
            start = Color(0xFF4F6AF6),
            end = Color(0xFF38BDF8),
            angle = 135.toFloat()
        )
        val brand = GradientValues(
            start = Color(0xFF4F6AF6),
            end = Color(0xFF8B5CF6),
            angle = 135.toFloat()
        )
        val cyan = GradientValues(
            start = Color(0xFF06B6D4),
            end = Color(0xFF67E8F9),
            angle = 135.toFloat()
        )
        val green = GradientValues(
            start = Color(0xFF10B981),
            end = Color(0xFF34D399),
            angle = 135.toFloat()
        )
        val orange = GradientValues(
            start = Color(0xFFF59E0B),
            end = Color(0xFFFB923C),
            angle = 135.toFloat()
        )
        val peach = GradientValues(
            start = Color(0xFFFB7185),
            end = Color(0xFFFDBA74),
            angle = 135.toFloat()
        )
        val pink = GradientValues(
            start = Color(0xFFEC4899),
            end = Color(0xFFF472B6),
            angle = 135.toFloat()
        )
        val purple = GradientValues(
            start = Color(0xFF8B5CF6),
            end = Color(0xFFC084FC),
            angle = 135.toFloat()
        )
        val sky = GradientValues(
            start = Color(0xFF0EA5E9),
            end = Color(0xFF7DD3FC),
            angle = 135.toFloat()
        )
    }

}

data class ShadowValues(
    val offsetY: Dp,
    val blur: Dp,
    val opacity: Float
)

data class AnimationValues(
    val duration: Float,
    val damping: Float = 1.0f,
    val velocity: Float = 0.5f
)

data class GradientValues(
    val start: Color,
    val end: Color,
    val angle: Float
)
