#!/usr/bin/env swift
//
// sync-design-tokens.swift
// WebBridgeKit — Design Token Sync Tool
//
// Reads docs/design-tokens.json → generates:
//   A) Sources/Theme/ThemeTokens.swift (iOS)
//   B) docs/prototype/design-tokens.css (CSS)
//   C) Validation report (stdout)
//
// AUTO-GENERATED — do not edit ThemeTokens.swift or design-tokens.css by hand.
//

import Foundation

// MARK: - Paths

let projectRoot = FileManager.default.currentDirectoryPath
let tokensPath = projectRoot + "/docs/design-tokens.json"
let schemaPath = projectRoot + "/docs/design-tokens.schema.json"
let swiftOutputPath = projectRoot + "/Sources/Theme/ThemeTokens.swift"
let cssOutputPath = projectRoot + "/docs/prototype/design-tokens.css"

let autoGenHeader = """
// ============================================================
// ⚠️ AUTO-GENERATED by tools/sync-design-tokens.swift
// DO NOT EDIT — changes will be overwritten on next sync.
// Source: docs/design-tokens.json
// Generated: \(ISO8601DateFormatter().string(from: Date()))
// ============================================================

"""

// MARK: - JSON Loading

struct DesignTokens: Codable {
    let version: String
    let colors: ColorsSection
    let typography: [String: TypographyToken]
    let spacing: [String: Double]
    let cornerRadius: [String: Double]
    let shadows: [String: ShadowToken]
    let opacity: [String: Double]
    let animation: [String: AnimationToken]
    let icon: [String: Double]
    let componentContracts: [String: [String: ContractValue]]?

    struct ColorsSection: Codable {
        let light: [String: String]
        let dark: [String: String]
    }

    struct TypographyToken: Codable {
        let size: Double
        let weight: String
        let tracking: Double?
    }

    struct ShadowToken: Codable {
        let color: String?
        let opacity: Double
        let offsetX: Double
        let offsetY: Double
        let radius: Double
    }

    struct AnimationToken: Codable {
        let duration: Double
        let curve: String
        let damping: Double?
    }
}

enum ContractValue: Codable, Equatable {
    case doubleValue(Double)
    case boolValue(Bool)
    case intValue(Int)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let b = try? container.decode(Bool.self) {
            self = .boolValue(b)
        } else if let d = try? container.decode(Double.self) {
            self = .doubleValue(d)
        } else if let i = try? container.decode(Int.self) {
            self = .intValue(i)
        } else {
            self = .doubleValue(0)
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .doubleValue(let v): try container.encode(v)
        case .boolValue(let v): try container.encode(v)
        case .intValue(let v): try container.encode(v)
        }
    }

    var swiftLiteral: String {
        switch self {
        case .doubleValue(let v): return String(v)
        case .boolValue(let v): return v ? "true" : "false"
        case .intValue(let v): return String(v)
        }
    }

    var swiftType: String {
        switch self {
        case .boolValue: return "Bool"
        default: return "CGFloat"
        }
    }

    var cssLiteral: String {
        switch self {
        case .doubleValue(let v): return "\(Int(v))px"
        case .boolValue: return "" // bools don't become CSS vars
        case .intValue(let v): return "\(v)px"
        }
    }
}

func loadTokens() -> DesignTokens? {
    guard let data = FileManager.default.contents(atPath: tokensPath) else {
        print("❌ ERROR: Cannot read \(tokensPath)")
        return nil
    }
    do {
        return try JSONDecoder().decode(DesignTokens.self, from: data)
    } catch {
        print("❌ ERROR: Failed to parse design-tokens.json: \(error)")
        return nil
    }
}

// MARK: - Color Parsing

func parseHex(_ hex: String) -> (r: Double, g: Double, b: Double, a: Double)? {
    let cleaned = hex.trimmingCharacters(in: .whitespacesAndNewlines)
      .replacingOccurrences(of: "#", with: "")

    if cleaned.hasPrefix("rgba") || cleaned.hasPrefix("rgb") {
        let nums = cleaned
            .replacingOccurrences(of: "rgba", with: "")
            .replacingOccurrences(of: "rgb", with: "")
            .replacingOccurrences(of: "(", with: "")
            .replacingOccurrences(of: ")", with: "")
            .replacingOccurrences(of: " ", with: "")
            .split(separator: ",")
            .compactMap { Double($0) }
        if nums.count >= 3 {
            let a = nums.count >= 4 ? nums[3] : 1.0
            return (r: nums[0] / 255.0, g: nums[1] / 255.0, b: nums[2] / 255.0, a: a)
        }
        return nil
    }

    var r: UInt64 = 0, g: UInt64 = 0, b: UInt64 = 0, a: UInt64 = 255
    switch cleaned.count {
    case 6:
        Scanner(string: String(cleaned.prefix(2))).scanHexInt64(&r)
        Scanner(string: String(cleaned.dropFirst(2).prefix(2))).scanHexInt64(&g)
        Scanner(string: String(cleaned.dropFirst(4).prefix(2))).scanHexInt64(&b)
    case 8:
        Scanner(string: String(cleaned.prefix(2))).scanHexInt64(&r)
        Scanner(string: String(cleaned.dropFirst(2).prefix(2))).scanHexInt64(&g)
        Scanner(string: String(cleaned.dropFirst(4).prefix(2))).scanHexInt64(&b)
        Scanner(string: String(cleaned.dropFirst(6).prefix(2))).scanHexInt64(&a)
    case 3:
        Scanner(string: String(repeating: String(cleaned.prefix(1)), count: 2)).scanHexInt64(&r)
        Scanner(string: String(repeating: String(cleaned.dropFirst(1).prefix(1)), count: 2)).scanHexInt64(&g)
        Scanner(string: String(repeating: String(cleaned.dropFirst(2).prefix(1)), count: 2)).scanHexInt64(&b)
    default:
        return nil
    }
    return (r: Double(r) / 255.0, g: Double(g) / 255.0, b: Double(b) / 255.0, a: Double(a) / 255.0)
}

func swiftUIColorExpr(_ hex: String) -> String {
    guard let c = parseHex(hex) else { return "UIColor(red: 0, green: 0, blue: 0, alpha: 1) /* PARSE ERROR: \(hex) */" }
    if c.a < 1.0 {
        return "UIColor(red: \(c.r), green: \(c.g), blue: \(c.b), alpha: \(c.a))"
    }
    return "UIColor(red: \(c.r), green: \(c.g), blue: \(c.b), alpha: 1)"
}

func cssColor(_ hex: String) -> String {
    guard let c = parseHex(hex) else { return hex }
    if c.a < 1.0 {
        return "rgba(\(Int(c.r * 255)), \(Int(c.g * 255)), \(Int(c.b * 255)), \(c.a))"
    }
    return "rgb(\(Int(c.r * 255)), \(Int(c.g * 255)), \(Int(c.b * 255)))"
}

func weightToSwift(_ w: String) -> String {
    switch w {
    case "ultralight": return ".ultraLight"
    case "light": return ".light"
    case "regular": return ".regular"
    case "medium": return ".medium"
    case "semibold": return ".semibold"
    case "bold": return ".bold"
    case "heavy": return ".heavy"
    default: return ".regular"
    }
}

let typographyTextStyleMap: [String: String] = [
    "screenTitle": ".largeTitle",
    "compactTitle": ".title1",
    "sectionTitle": ".headline",
    "rowTitle": ".body",
    "cardTitle": ".subheadline",
    "body": ".body",
    "metadata": ".footnote",
    "caption": ".caption1",
    "badge": ".caption2",
    "tabLabel": ".caption2",
    "button": ".body",
    "buttonMedium": ".body",
]

func textStyleForKey(_ key: String) -> String {
    return typographyTextStyleMap[key] ?? ".body"
}

func capitalizeFirst(_ s: String) -> String {
    guard let first = s.first else { return s }
    return String(first).uppercased() + s.dropFirst()
}

func generateDynamicColorAlias(_ key: String) -> String {
    "        public static var \(key): UIColor { dynamicColor(light: Colors.Light.\(key), dark: Colors.Dark.\(key)) }"
}

// MARK: - Generate ThemeTokens.swift

func generateSwift(_ tokens: DesignTokens) -> String {
    var lines: [String] = []
    lines.append("import UIKit")
    lines.append("")
    lines.append(autoGenHeader)
    lines.append("public enum ThemeTokens {")
    lines.append("")

    // Colors
    lines.append("    // DEPRECATED: Use ThemeTokens.Color instead (auto-adapts to Dark Mode)")
    lines.append("    public enum Colors {")
    lines.append("        public enum Light {")
    let lightKeys = tokens.colors.light.keys.sorted()
    for key in lightKeys {
        let val = tokens.colors.light[key]!
        lines.append("            public static let \(key) = \(swiftUIColorExpr(val))")
    }
    lines.append("        }")
    lines.append("")
    lines.append("        public enum Dark {")
    let darkKeys = tokens.colors.dark.keys.sorted()
    for key in darkKeys {
        let val = tokens.colors.dark[key]!
        lines.append("            public static let \(key) = \(swiftUIColorExpr(val))")
    }
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    // Dynamic Colors
    lines.append("    // === Dynamic Color aliases (the ONE way to get colors) ===")
    lines.append("    /// Dynamic color tokens — auto-adapt to Light/Dark Mode.")
    lines.append("    /// New code must use ThemeTokens.Color.* instead of ThemeTokens.Colors.Light/Dark or hardcoded UIColor values.")
    lines.append("    public enum Color {")
    let colorKeys = lightKeys.filter { tokens.colors.dark[$0] != nil }
    for key in colorKeys {
        lines.append(generateDynamicColorAlias(key))
    }
    lines.append("")
    lines.append("        // Compatibility aliases used by existing components.")
    lines.append("        public static var divider: UIColor { separator }")
    lines.append("        public static var navigationBarTitle: UIColor { text }")
    lines.append("        public static var iconBackground: UIColor { primary.withAlphaComponent(0.1) }")
    lines.append("        public static var dimOverlay: UIColor { overlay }")
    lines.append("        public static var secondary: UIColor { textSecondary }")
    lines.append("        public static var textOnColor: UIColor { dynamicColor(light: .white, dark: .white) }")
    lines.append("        public static var onPrimary: UIColor { textOnColor }")
    lines.append("        public static var badgeBackground: UIColor { dynamicColor(light: Colors.Light.primarySoft, dark: Colors.Dark.primarySoft) }")
    lines.append("        public static var badgeText: UIColor { textSecondary }")
    lines.append("        public static var fabBackground: UIColor { primary }")
    lines.append("        public static var gradientEnd: UIColor { dynamicColor(light: UIColor(red: 0.6, green: 0.302, blue: 0.749, alpha: 0.85), dark: UIColor(red: 0.4, green: 0.2, blue: 0.502, alpha: 0.9)) }")
    lines.append("        public static var gradientStart: UIColor { dynamicColor(light: UIColor(red: 0.251, green: 0.451, blue: 0.949, alpha: 0.85), dark: UIColor(red: 0.2, green: 0.302, blue: 0.6, alpha: 0.9)) }")
    lines.append("        public static var unreadDot: UIColor { primary }")
    lines.append("        public static var scrim: UIColor { overlay }")
    lines.append("        public static var overlayStrong: UIColor { dynamicColor(light: UIColor(red: 0.067, green: 0.094, blue: 0.153, alpha: 0.7), dark: UIColor(red: 0, green: 0, blue: 0, alpha: 0.8)) }")
    lines.append("        public static var overlaySoft: UIColor { dynamicColor(light: UIColor(red: 0.067, green: 0.094, blue: 0.153, alpha: 0.2), dark: UIColor(red: 0, green: 0, blue: 0, alpha: 0.3)) }")
    lines.append("")
    lines.append("        private static func dynamicColor(light: UIColor, dark: UIColor) -> UIColor {")
    lines.append("            UIColor { trait in")
    lines.append("                trait.userInterfaceStyle == .dark ? dark : light")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    // Typography
    lines.append("    public enum Typography {")
    let typoKeys = tokens.typography.keys.sorted()
    for key in typoKeys {
        let t = tokens.typography[key]!
        let w = weightToSwift(t.weight)
        let textStyle = textStyleForKey(key)
        lines.append("        public static let \(key) = UIFontMetrics(forTextStyle: \(textStyle)).scaledFont(for: .systemFont(ofSize: \(Int(t.size)), weight: \(w)))")
    }
    // Extra typography tokens used by existing components
    lines.append("        public static let buttonMedium = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .medium))")
    lines.append("        public static let badge = UIFontMetrics(forTextStyle: .caption2).scaledFont(for: .systemFont(ofSize: 10, weight: .bold))")
    lines.append("")
    lines.append("        // Monospace variants")
    lines.append("        public static let monospaceMetaBold = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 12, weight: .bold))")
    lines.append("        public static let monospaceBody = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 13, weight: .regular))")
    lines.append("        public static let monospaceBodyMedium = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 13, weight: .medium))")
    lines.append("        public static let monospaceSmall = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 11, weight: .regular))")
    lines.append("        public static let monospaceSmallMedium = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 11, weight: .medium))")
    lines.append("        public static let monospaceMini = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 10, weight: .regular))")
    lines.append("        public static let monospaceMiniMedium = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 10, weight: .medium))")
    lines.append("        public static let monospaceMicro = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 9, weight: .regular))")
    lines.append("        public static let monospaceLarge = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 14, weight: .regular))")
    lines.append("        public static let monospaceLargeMedium = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 14, weight: .medium))")
    lines.append("        public static let monospaceLargeSemibold = UIFontMetrics(forTextStyle: .body).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 17, weight: .semibold))")
    lines.append("        public static let monospaceTitle = UIFontMetrics(forTextStyle: .title3).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 18, weight: .bold))")
    lines.append("        public static let monospaceDisplay = UIFontMetrics(forTextStyle: .title2).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 20, weight: .bold))")
    lines.append("        public static let monospaceDisplaySemibold = UIFontMetrics(forTextStyle: .title2).scaledFont(for: UIFont.monospacedSystemFont(ofSize: 20, weight: .semibold))")
    lines.append("")
    lines.append("        // Legacy Apple text style aliases")
    lines.append("        public static let largeTitle = UIFontMetrics(forTextStyle: .largeTitle).scaledFont(for: .systemFont(ofSize: 28, weight: .bold))")
    lines.append("        public static let title1 = UIFontMetrics(forTextStyle: .largeTitle).scaledFont(for: .systemFont(ofSize: 28, weight: .bold))")
    lines.append("        public static let title2 = UIFontMetrics(forTextStyle: .title1).scaledFont(for: .systemFont(ofSize: 24, weight: .bold))")
    lines.append("        public static let title3 = UIFontMetrics(forTextStyle: .subheadline).scaledFont(for: .systemFont(ofSize: 16, weight: .semibold))")
    lines.append("        public static let headline = UIFontMetrics(forTextStyle: .headline).scaledFont(for: .systemFont(ofSize: 17, weight: .semibold))")
    lines.append("        public static let subheadline = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .regular))")
    lines.append("        public static let callout = UIFontMetrics(forTextStyle: .body).scaledFont(for: .systemFont(ofSize: 15, weight: .regular))")
    lines.append("        public static let footnote = UIFontMetrics(forTextStyle: .footnote).scaledFont(for: .systemFont(ofSize: 13, weight: .regular))")
    lines.append("        public static let caption1 = UIFontMetrics(forTextStyle: .caption1).scaledFont(for: .systemFont(ofSize: 12, weight: .regular))")
    lines.append("        public static let caption2 = UIFontMetrics(forTextStyle: .caption2).scaledFont(for: .systemFont(ofSize: 11, weight: .medium))")
    lines.append("    }")
    lines.append("")

    // Spacing
    lines.append("    public enum Spacing {")
    let spacingKeys = tokens.spacing.keys.sorted()
    for key in spacingKeys {
        let val = tokens.spacing[key]!
        lines.append("        public static let \(key): CGFloat = \(val)")
    }
    lines.append("    }")
    lines.append("")

    // CornerRadius
    lines.append("    public enum CornerRadius {")
    let radiusKeys = tokens.cornerRadius.keys.sorted()
    for key in radiusKeys {
        let val = tokens.cornerRadius[key]!
        lines.append("        public static let \(key): CGFloat = \(val)")
    }
    // Legacy aliases
    lines.append("        public static let lg: CGFloat = 12.0")
    lines.append("        public static let xl: CGFloat = 16.0")
    lines.append("        public static let xxl: CGFloat = 20.0")
    lines.append("        public static let avatar: CGFloat = 22.0")
    lines.append("        public static let pill: CGFloat = 28.0")
    lines.append("    }")
    lines.append("    public enum Shadows {")
    let shadowKeys = tokens.shadows.keys.sorted()
    for key in shadowKeys {
        let s = tokens.shadows[key]!
        lines.append("        public static let \(key) = ShadowValues(opacity: \(s.opacity), offsetX: \(s.offsetX), offsetY: \(s.offsetY), radius: \(s.radius))")
    }
    // Legacy PascalCase aliases
    lines.append("        public static let Card = ShadowValues(opacity: 1, offsetX: 0, offsetY: 2, radius: 8)")
    lines.append("        public static let Fab = ShadowValues(opacity: 1, offsetX: 0, offsetY: 8, radius: 18)")
    lines.append("        public static let Modal = ShadowValues(opacity: 1, offsetX: 0, offsetY: 12, radius: 28)")
    lines.append("        public static let NavBar = ShadowValues(opacity: 0, offsetX: 0, offsetY: 0, radius: 0)")
    lines.append("        public static let SearchBar = ShadowValues(opacity: 0, offsetX: 0, offsetY: 0, radius: 0)")
    lines.append("        public static let Tooltip = ShadowValues(opacity: 0, offsetX: 0, offsetY: 0, radius: 0)")
    lines.append("    }")
    lines.append("")

    // Opacity
    lines.append("    public enum Opacity {")
    let opacityKeys = tokens.opacity.keys.sorted()
    for key in opacityKeys {
        let val = tokens.opacity[key]!
        lines.append("        public static let \(key): CGFloat = \(val)")
    }
    // Legacy aliases
    lines.append("        public static let badge: CGFloat = 0.14")
    lines.append("        public static let overlay: CGFloat = 0.42")
    lines.append("        public static let hover: CGFloat = 0.72")
    lines.append("        public static let placeholder: CGFloat = 0.36")
    lines.append("    }")
    lines.append("")

    // Animation
    lines.append("    public enum Animation {")
    let animKeys = tokens.animation.keys.sorted()
    for key in animKeys {
        let a = tokens.animation[key]!
        let dampingSuffix: String
        if let d = a.damping {
            dampingSuffix = ", damping: \(d)"
        } else {
            dampingSuffix = ""
        }
        lines.append("        public static let \(key) = AnimationValues(duration: \(a.duration)\(dampingSuffix))")
    }
    // Legacy aliases
    lines.append("        public static let modal = AnimationValues(duration: 0.36, damping: 0.88)")
    lines.append("        public static let slow = AnimationValues(duration: 0.22)")
    lines.append("    }")
    lines.append("")

    // Icons
    lines.append("    public enum Icons {")
    lines.append("        public enum Sizes {")
    let iconKeys = tokens.icon.keys.sorted()
    for key in iconKeys {
        let val = tokens.icon[key]!
        lines.append("            public static let \(key): CGFloat = \(val)")
    }
    // Legacy aliases
    lines.append("            public static let xxl: CGFloat = 48.0")
    lines.append("            public static let xl: CGFloat = 24.0")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    // Breakpoints (hardcoded since not in JSON)
    lines.append("    public enum Breakpoints {")
    lines.append("        public static let compact: CGFloat = 320.0")
    lines.append("        public static let regular: CGFloat = 375.0")
    lines.append("        public static let large: CGFloat = 428.0")
    lines.append("    }")
    lines.append("")

    // Component Contracts
    if let contracts = tokens.componentContracts {
        lines.append("    public enum ComponentContract {")
        let contractKeys = contracts.keys.sorted()
        for contractName in contractKeys {
            let pascalName = capitalizeFirst(contractName)
            lines.append("        public enum \(pascalName) {")
            let props = contracts[contractName]!
            let propKeys = props.keys.sorted()
            for propKey in propKeys {
                let val = props[propKey]!
                lines.append("            public static let \(propKey): \(val.swiftType) = \(val.swiftLiteral)")
            }
            lines.append("        }")
        }
        lines.append("    }")
        lines.append("")
    }

    lines.append("}")

    // Supporting types
    lines.append("")
    lines.append("public struct ShadowValues: Sendable {")
    lines.append("    public let opacity: CGFloat")
    lines.append("    public let offsetX: CGFloat")
    lines.append("    public let offsetY: CGFloat")
    lines.append("    public let radius: CGFloat")
    lines.append("}")
    lines.append("")
    lines.append("public struct AnimationValues: Sendable {")
    lines.append("    public let duration: TimeInterval")
    lines.append("    public let damping: CGFloat")
    lines.append("")
    lines.append("    public init(duration: TimeInterval, damping: CGFloat = 1.0) {")
    lines.append("        self.duration = duration")
    lines.append("        self.damping = damping")
    lines.append("    }")
    lines.append("}")

    return lines.joined(separator: "\n") + "\n"
}

// MARK: - Generate design-tokens.css

func generateCSS(_ tokens: DesignTokens) -> String {
    var lines: [String] = []
    lines.append("/*")
    lines.append(" * ⚠️ AUTO-GENERATED by tools/sync-design-tokens.swift")
    lines.append(" * DO NOT EDIT — changes will be overwritten on next sync.")
    lines.append(" * Source: docs/design-tokens.json")
    lines.append(" */")
    lines.append("")

    // :root (light)
    lines.append(":root {")
    let lightKeys = tokens.colors.light.keys.sorted()
    for key in lightKeys {
        lines.append("  --color-\(key): \(cssColor(tokens.colors.light[key]!));")
    }
    lines.append("")
    let spacingKeys = tokens.spacing.keys.sorted()
    for key in spacingKeys {
        lines.append("  --spacing-\(key): \(Int(tokens.spacing[key]!))px;")
    }
    lines.append("")
    let radiusKeys = tokens.cornerRadius.keys.sorted()
    for key in radiusKeys {
        lines.append("  --radius-\(key): \(Int(tokens.cornerRadius[key]!))px;")
    }
    lines.append("")
    let typoKeys = tokens.typography.keys.sorted()
    for key in typoKeys {
        let t = tokens.typography[key]!
        lines.append("  --font-\(key)-size: \(Int(t.size))px;")
        lines.append("  --font-\(key)-weight: \(t.weight);")
    }
    lines.append("")
    let opacityKeys = tokens.opacity.keys.sorted()
    for key in opacityKeys {
        lines.append("  --opacity-\(key): \(tokens.opacity[key]!);")
    }
    lines.append("")
    let shadowKeys = tokens.shadows.keys.sorted()
    for key in shadowKeys {
        let s = tokens.shadows[key]!
        lines.append("  --shadow-\(key): 0 \(Int(s.offsetY))px \(Int(s.radius))px rgba(0,0,0,\(s.opacity));")
    }
    lines.append("")
    let iconKeys = tokens.icon.keys.sorted()
    for key in iconKeys {
        let val = tokens.icon[key]!
        lines.append("  --icon-\(key): \(Int(val))px;")
    }
    lines.append("")
    if let contracts = tokens.componentContracts {
        let contractKeys = contracts.keys.sorted()
        for contractName in contractKeys {
            let props = contracts[contractName]!
            let propKeys = props.keys.sorted()
            for propKey in propKeys {
                let val = props[propKey]!
                let cssVal = val.cssLiteral
                if !cssVal.isEmpty {
                    lines.append("  --contract-\(contractName)-\(propKey): \(cssVal);")
                }
            }
        }
    }
    lines.append("}")
    lines.append("")

    // @media (prefers-color-scheme: dark)
    lines.append("@media (prefers-color-scheme: dark) {")
    lines.append("  :root {")
    let darkKeys = tokens.colors.dark.keys.sorted()
    for key in darkKeys {
        lines.append("    --color-\(key): \(cssColor(tokens.colors.dark[key]!));")
    }
    lines.append("  }")
    lines.append("}")
    lines.append("")

    // [data-theme="dark"] manual override
    lines.append("[data-theme=\"dark\"] {")
    for key in darkKeys {
        lines.append("  --color-\(key): \(cssColor(tokens.colors.dark[key]!));")
    }
    lines.append("}")

    return lines.joined(separator: "\n") + "\n"
}

// MARK: - Validation Report

func printValidationReport(_ tokens: DesignTokens) {
    print("")
    print("═══════════════════════════════════════════")
    print("  Design Token Validation Report")
    print("═══════════════════════════════════════════")
    print("")

    // Count tokens
    let colorCount = tokens.colors.light.count + tokens.colors.dark.count
    let typoCount = tokens.typography.count
    let spacingCount = tokens.spacing.count
    let radiusCount = tokens.cornerRadius.count
    let shadowCount = tokens.shadows.count
    let opacityCount = tokens.opacity.count
    let animCount = tokens.animation.count
    let iconSizeCount = tokens.icon.count
    let contractCount = tokens.componentContracts?.reduce(0) { $0 + $1.value.count } ?? 0
    let total = colorCount + typoCount + spacingCount + radiusCount + shadowCount + opacityCount + animCount + iconSizeCount + contractCount

    print("  Tokens by category:")
    print("    Colors:       \(colorCount) (\(tokens.colors.light.count) light + \(tokens.colors.dark.count) dark)")
    print("    Typography:   \(typoCount)")
    print("    Spacing:      \(spacingCount)")
    print("    CornerRadius: \(radiusCount)")
    print("    Shadows:      \(shadowCount)")
    print("    Opacity:      \(opacityCount)")
    print("    Animation:    \(animCount)")
    print("    Icon sizes:   \(iconSizeCount)")
    print("    Contracts:    \(contractCount)")
    print("    ────────────────────")
    print("    TOTAL:        \(total)")
    print("")

    // Check light/dark parity
    let lightSet = Set(tokens.colors.light.keys)
    let darkSet = Set(tokens.colors.dark.keys)
    let missingDark = lightSet.subtracting(darkSet)
    let missingLight = darkSet.subtracting(lightSet)

    if missingDark.isEmpty && missingLight.isEmpty {
        print("  ✅ Color parity: light and dark palettes have identical keys")
    } else {
        if !missingDark.isEmpty {
            print("  ⚠️  Missing from dark: \(missingDark.sorted().joined(separator: ", "))")
        }
        if !missingLight.isEmpty {
            print("  ⚠️  Missing from light: \(missingLight.sorted().joined(separator: ", "))")
        }
    }

    // Validate all colors are parseable
    var parseErrors: [(String, String)] = []
    for (key, hex) in tokens.colors.light {
        if parseHex(hex) == nil {
            parseErrors.append(("light.\(key)", hex))
        }
    }
    for (key, hex) in tokens.colors.dark {
        if parseHex(hex) == nil {
            parseErrors.append(("dark.\(key)", hex))
        }
    }
    if parseErrors.isEmpty {
        print("  ✅ Color values: all parseable")
    } else {
        for (path, val) in parseErrors {
            print("  ❌ Unparseable color: \(path) = \(val)")
        }
    }
    print("")
}

// MARK: - Main

guard let tokens = loadTokens() else {
    print("Failed to load tokens. Exiting.")
    exit(1)
}

print("✅ Loaded design-tokens.json v\(tokens.version)")

// Generate Swift
let swiftCode = generateSwift(tokens)
let swiftDir = (swiftOutputPath as NSString).deletingLastPathComponent
try? FileManager.default.createDirectory(atPath: swiftDir, withIntermediateDirectories: true)
FileManager.default.createFile(atPath: swiftOutputPath, contents: swiftCode.data(using: .utf8))
print("✅ Written: \(swiftOutputPath)")

// Generate CSS
let cssCode = generateCSS(tokens)
let cssDir = (cssOutputPath as NSString).deletingLastPathComponent
try? FileManager.default.createDirectory(atPath: cssDir, withIntermediateDirectories: true)
FileManager.default.createFile(atPath: cssOutputPath, contents: cssCode.data(using: .utf8))
print("✅ Written: \(cssOutputPath)")

// Validation report
printValidationReport(tokens)

print("═══════════════════════════════════════════")
print("  Sync complete.")
print("═══════════════════════════════════════════")
